### ISSUE TITLE
Syntax / Nested fields in Dev

### ISSUE THREAD

**Issue by JoshZA** [kazupon/vue-validator#100]
Hey Kazupon

I have this use case

```
v-model="client.description"
v-validate:client.description.required
```

Does validator 2.0 support nested properties?

Is their no way to change v2 to automatically get the binding from v-model, so that we could just write

```
v-model="client.description"
v-validate:required
```

Also for this:

```
    ID: <input type="text" v-validate:id.minlength.maxlength="{ minlength: 3, maxlength: 16 }"><br />
```

Couldn't we get:

```
    ID: <input type="text" v-validate:id.minlength(3).maxlength(16)><br />
```

**Comment by bradstewart** [comment]
You can do something like:

``` html
<validator name="clientValidator">
  <input v-model="client.description" v-validate:description.required />
</validator>
```

And then in your Vue instance, `this.$clientValidator.description` will contain the value of the input field and all the relevant validation data for the field.

**Comment by kazupon** [comment]
Sorry for the late reply.

In v2.0, I decided that don't support the nested property, because application design become complex. Vue is the component oriented. I think that you can implement like the comment of @bradstewart, also use the component.

**Comment by JoshZA** [comment]
Ah ok, makes sense, thanks guys =)
