### ISSUE TITLE
2.0.0-alpha.6 not on npm

### ISSUE THREAD

**Issue by karol-f** [kazupon/vue-validator#104]
NPM version of vue-validator does not contain latest release - https://www.npmjs.com/package/vue-validator.

Regards

**Comment by kazupon** [comment]
ah, sorry ... :bow: 
I published now. :cat:

**Comment by karol-f** [comment]
Great!

**Comment by miljan-aleksic** [comment]
This seems wasn't addressed? I'm getting the 1.4.4 version.

**Comment by karol-f** [comment]
@miljan-aleksic I'm using it and have right version. Probably you are using something like this:
`"vue-validator": "^2.0.0"`

instead of this:
`"vue-validator": "^2.0.0-beta.6"`

Or the problem is different? Regards.

**Comment by miljan-aleksic** [comment]
Actually I just did `npm install vue-validator --save` expecting it would get the latest version, but maybe only does that for stable ones. Will use your suggestion, tks.
