### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by barbabravo** [kazupon/vue-validator#105]
Hi, guys
I am using vue-validate 1.4.4 and vue 1.0.10, and webpack example has thrown error like
`
Cannot convert undefined or null to object
`

But using vue 0.12 is correct;

Has someone found this problem?

**Comment by kazupon** [comment]
Sorry, vue-validator 1.x don't support.
The vue-validator 1.x cannot run the in 1.0.x because it use deprecated API of Vue.

I hope to you will upgrade vue-validator 2.0.0-alpha. :cat:
