### ISSUE TITLE
Unable to make work vue-validator with vue 1.0.11

### ISSUE THREAD

**Issue by cgarnier** [kazupon/vue-validator#107]
Hello,
This module doesnt work with 1.0.11.
I had to use the dev branch.
The exemples are totaly out of date and the documentation is really ligth :P.

Please, could you make a new release ?

**Comment by kazupon** [comment]
Thank you for reporting !!

> This module doesnt work with 1.0.11.

Please provide the reproduction code by jsfiddle, codepen, etc.

> The exemples are totaly out of date and the documentation is really light

Sorry. :smile_cat: 
Every time I publish vue-validator, I'll improve the documentation.

**Comment by cgarnier** [comment]
I dont think codepen will be usefull because you already fixed it on the dev.
I have some forms to validate. 
If i find something i willl tell you.

**Comment by kazupon** [comment]
inactive
