### ISSUE TITLE
哥们 api是不是更新了？

### ISSUE THREAD

**Issue by lazyhero** [kazupon/vue-validator#110]
文档中的
Vue.validate('email', function (val) {
        return /^(([^<>()[]\.,;:\s@\"]+(.[^<>()[]\.,;:\s@\"]+)*)|(\".+\"))@(([[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}])|(([a-zA-Z-0-9]+.)+[a-zA-Z]{2,}))$/.test(val)
    })
validate是不是换成validator了？

**Comment by kazupon** [comment]
Thank you for your reporting :smile_cat: 

Can you comment with English ?

**Comment by lazyhero** [comment]
e my english so poor……
I found a question that there a change in API ,but it don't  make correct in document.
The question is that  'Vue.validate' be changed Vue.validator.
if you use Vue.validate the console show 'undefined'
if you use Vue.validator all will be work
I feel sad for my english teacher……

**Comment by kazupon** [comment]
Thanks !!

I understood.
Sorry. 
I'll try to fix now. :smile_cat:
