### ISSUE TITLE
How to validate radio/checkbox?

### ISSUE THREAD

**Issue by erguotou520** [kazupon/vue-validator#115]
The `text` input field works fine in `v2.0.0-alpha.8`, but not works on `radio` and `checkbox`, no test on other field.

**Comment by kazupon** [comment]
Thank you for your feedback!
I'll try to support recently. :smile_cat: 
please wait.

**Comment by kazupon** [comment]
Published v2.0.0-alpha.9
https://github.com/vuejs/vue-validator/releases/tag/v2.0.0-alpha.9

**Comment by erguotou520** [comment]
Nice job!
