### ISSUE TITLE
how can the messages be right according to the components order?

### ISSUE THREAD

**Issue by lmnsg** [kazupon/vue-validator#117]
I have a form, it just have one message wrapper to show error message,
and I want the error message can be right according to the components order.
Now, the $validate.messages object can not help me.
what shall I do?

**Comment by kazupon** [comment]
Thank you for your feedback :smile_cat: 

Can you provide the sample codes (with jsfiddle or codepen or etc)?

**Comment by lmnsg** [comment]
@kazupon right, I add the simple [codes](https://jsfiddle.net/1xfhzbvz/2/) on jsfiddle, just show you my need. 
if you can read.......

**Comment by kazupon** [comment]
@lmnsg 
Thank you for your codes :smile_cat: 
I checked your code.

I guess that occurred the following error.

```
Uncaught TypeError: value.toString is not a function
```

Can you provide me the your stack trace when occured error at your enviroment ?

**Comment by kazupon** [comment]
close inactive
