### ISSUE TITLE
The examples of dynamic model does not work

### ISSUE THREAD

**Issue by cn2156** [kazupon/vue-validator#123]
In firefox 43 linux, the examples does not work in this issue https://github.com/vuejs/vue-validator/issues/14

Details:
https://jsfiddle.net/kazupon/xkkcrzn7/5/
https://jsfiddle.net/cwjtta99/7/
https://jsfiddle.net/cwjtta99/8/

How to compatible with vue 1.0.13 and vue-validator 2.0.0-alpha.9 ?
Thanks a lot.

**Comment by kazupon** [comment]
Sorry, :bow: 
vue-validator 1.x syntax is not compatible for 2.0-alpha or later, because vue-validator 1.x don't work for vue 1.0

You need to re-implement with new 2.0 syntax. :smile_cat:
