### ISSUE TITLE
validator for list rendering

### ISSUE THREAD

**Issue by KingMario** [kazupon/vue-validator#126]
When adding a validator for a list, is it possible to name the v-validator with $index as suffix, say, v-validator:username-0, v-validator:username-1, ...?

Otherwise, if name all the validators with uinque name, maybe the validators can be treated as an array?

Currently, the validator for list rendering behaves weird. Seems that the validator gets lost when the list rerendered.

[jsfiddle](https://jsfiddle.net/KingMario/03wedezz/)

**Comment by kazupon** [comment]
> When adding a validator for a list, is it possible to name the v-validator with $index as suffix, say, v-validator:username-0, v-validator:username-1, ...?
> Otherwise, if name all the validators with uinque name, maybe the validators can be treated as an array?

So far, vue-validator cannot name your desired, and validators cannot be treated as array.
Currently, I think that you can avoid this issue by using wrapped validator with component.

However, vue-validator might be support the convenient syntax for list.
Could you provide the pseudo code ?

> Currently, the validator for list rendering behaves weird. Seems that the validator gets lost when the list rerendered.

Thank you for your reporting.
I checked your jsfiddle.
As you say, vie-validator is running the strange behavior.
I'll try to fix. :smile_cat:

**Comment by luqingxuan** [comment]
i have this problem too，so i am waiting，please can u give me the time when will resolve this problem？

**Comment by chestnutchen** [comment]
+1

**Comment by kazupon** [comment]
Related #173
Maybe, you need to wrap the $index with method.

**Comment by kazupon** [comment]
released v3.0.0-alpha.1
https://github.com/vuejs/vue-validator/releases/tag/v3.0.0-alpha.1

see the [example](https://github.com/vuejs/vue-validator/blob/dev/examples/dynamic/index.html)
