### ISSUE TITLE
NS_ERROR_UNEXPECTED on Firefox

### ISSUE THREAD

**Issue by losadaem** [kazupon/vue-validator#132]
Firefox has a bug where calling dispatchEvent on a non-attached and disabled input.

https://bugzilla.mozilla.org/show_bug.cgi?id=867418

jsfiddle:
https://jsfiddle.net/tm8LnLoo/

**Comment by losadaem** [comment]
Besides the Firefox bug it is worth considering if a disabled input needs to be validated.

**Comment by kazupon** [comment]
Thank you for your advise 😉
