### ISSUE TITLE
Disable validation in a form field.

### ISSUE THREAD

**Issue by lionellbriones** [kazupon/vue-validator#134]
How can i disable validation on "v-validate:addon" if water is select? 
I tried to use v-if instead of v-show to hide the input field but it causes the radio buttons to stop changing values. v-show only hides the field but keeps the validation on check.

Please check the jsfiddle code. thanks!

https://jsfiddle.net/llenoil/jLq9bukk/

**Comment by kazupon** [comment]
`v-if` directive  is terminal directive , and it is higher than `v-validate` directive. for this reason, when you specify `v-if` directive on the input tag which was specified `v-validate directive`, it does not work.

I came up with solution this issue.
https://jsfiddle.net/kazupon/yoobf7zd/1/

I hope my solution is useful for you. :smile_cat:

**Comment by neekychan** [comment]
Have anyother best solution?Have anyother best solution?

**Comment by kazupon** [comment]
I'll try to implement at v3.0.

**Comment by kazupon** [comment]
released v3.0.0-alpha.1
https://github.com/vuejs/vue-validator/releases/tag/v3.0.0-alpha.1
