### ISSUE TITLE
How to reset the "$validator1.modified" flag to unmodified?

### ISSUE THREAD

**Issue by hldgaofeng** [kazupon/vue-validator#136]
I  use a form in a dialog, My form will used many times after it is created,  and will not be destoryed.

How to reset the "$validator1.modified" flag to unmodified?

when user cancelling the dialog, I want to use the flag to detect is the form modified.

**Comment by kazupon** [comment]
See the https://github.com/vuejs/vue-validator#top-level-validation-properties

> modified: if modified field exist even one in validate fields, return true, else false.

You can reset the `modified` of top level, when you reset all fields value.

Do you want to reset with API  ?

**Comment by hldgaofeng** [comment]
Thanks for your response!
Yes, I want a API to reset form validator's modified state.

Example:

``` javascript
// modify form field values.
form.field1 = value1;
form.field2 = value2;
...
form.fieldn = valuen;

// reset validator's modified flag to "false".
form.$validator1.reset(); // will reset all field's modified state to "false"!!

```

**Comment by kazupon** [comment]
Thanks for your example codes!
I understood your request.
I'll try to add `reset` API. :smile_cat:
