### ISSUE TITLE
Does vue-validator support validation on fields inside a v-for element?

### ISSUE THREAD

**Issue by aaronjpitts** [kazupon/vue-validator#137]
I cannot get this to work on fields inside a v-for element. Is this possible with the current version?

Great work so far! Thank you

**Comment by kazupon** [comment]
Yes.
You can use the validation with `v-validate` inside `v-for` directive.
Example: 
https://github.com/vuejs/vue-validator/blob/dev/test/specs/directives/validate.js#L49

**Comment by aaronjpitts** [comment]
Hello, that's great! I've noticed one problem though, v-model causes the code to break if it's used on a field inside the view-directive with the for items name. For example, the below breaks the code:

```
<validator name="validator">
  <div v-for="room in property.rooms">
    <input type="text" v-model="room.price" :field="'field' + $index" v-validate="{ minlength: 4 }">
    <span v-if="$validator['field' + $index].valid"> valid !!</span>
  </div>
</validator>
```

It will give an error saying 'Uncaught TypeError: Cannot read property 'price' of undefined'

Thanks for your time so far. This is a great module.

**Comment by kazupon** [comment]
Thank you for your providing codes :smile_cat: 

I tried to reproduction `'Uncaught TypeError: Cannot read property 'price' of undefined'` error, However, I could not reproduction.

Can you provide the the following   info to me please ?
- vue.js version
- vue-validator version

**Comment by aaronjpitts** [comment]
Hi,

I'm using the latest of both:

vue.js: 1.0.14
vue-validator version: 2.0.0-alpha.12

**Comment by aaronjpitts** [comment]
Thank you very much for the prompt bug fix! :-) Great work!

**Comment by kwzm** [comment]
The link https://github.com/vuejs/vue-validator/blob/dev/test/specs/directives/validate.js#L49 is 404.

**Comment by zhoucumt** [comment]
hello ,I want to see this example: https://github.com/vuejs/vue-validator/blob/dev/test/specs/directives/validate.js#L49, but it is 404.Thank you!
