### ISSUE TITLE
How to add/remove a field from the $validation object if it's a field toggled by v-if?

### ISSUE THREAD

**Issue by aaronjpitts** [kazupon/vue-validator#138]
Hello again,

I have some fields which are shown via a v-if, basically they depend on another field's value. For example I have a field which is a boolean for 'housekeeping', if the input is set to true it shows another field to the user called 'housekeeping price'. This price is only required if 'housekeeping' is set to true. I've noticed that wrapping a v-if around 'housekeeping price' to only show the field if 'housekeeping' is set to true works fine to only include the field in the validation object once 'housekeeping' is set to true. The issue is that if the user then toggles 'housekeeping' to false (after setting it true )even though this hides the 'housekeeping price' field, the 'housekeeping price' field is still in the $validation object. Can we work with v-if to add and remove a field from the $validation object?

I hope this helps to explain what I'm trying to do:

```
    <h3>Houskeeping</h3>
    <input type="radio" v-model="housekeeping" id="true" value="true">
    <label for="true">Yes</label>
    <input type="radio" v-model="housekeeping" id="false" value="false">
    <label for="true">No</label>

    <div v-if="housekeeping">
        <h3>Houskeeping Price</h3>
        <input type="number" v-model="housekeepingPrice" v-validate:housekeeping-price="['required']">
    </div>
```

Thank you once again

**Comment by kazupon** [comment]
Thanks for your explain :smile_cat: 

> Can we work with v-if to add and remove a field from the $validation object?

Yes, when we used the `v-if`, we can remove / add (toggle like) from $validation scope.

I checked the your providing code, and I found the your mistake.

> <input type="radio" v-model="housekeeping" id="true" value="true">

The value of radio button is not boolean value but string value.
You should use the checkbox (single).

example:
https://jsfiddle.net/kazupon/ok2vaj3g/3/

However, in the above example, I found the bug. :scream: 
I'll try to fixed.

**Comment by aaronjpitts** [comment]
Hi, I've updated to your latest version (2.0.0-alpha.14) but if I toggle a field shown and then hidden within an v-if statement I get the below error:

vue-validator.common.js:1294 Uncaught TypeError: Cannot read property 'field' of null

**Comment by kazupon** [comment]
Sorry, I made a mistake.
Please use `v2.0.0-alpha.15` :arrow_up: 
https://github.com/vuejs/vue-validator/releases/tag/v2.0.0-alpha.15

**Comment by kazupon** [comment]
Close (in-activity)
