### ISSUE TITLE
v2.0.0-alpha.15 model issues when using the field attribute

### ISSUE THREAD

**Issue by lazabogdan** [kazupon/vue-validator#140]
The model doesn't update anymore when updating the field value. Also, notice in the example below the placeholder doesn't render.

See https://jsfiddle.net/lazabogdan/jjef94qn/
##### Off topic

Also, the validator updates only after a "blur" event. How can I have the previous behaviour, which validated each keystroke? Is there a configuration option for that? If not, please consider adding it.

**Comment by kazupon** [comment]
Thanks for your reporting!
I'll try to check your jsfiddle.

> How can I have the previous behaviour, which validated each keystroke?

Sorry, I could not understood.
I hope that you would provide the about the concrete use-case. :smile_cat:

**Comment by lazabogdan** [comment]
In v2.0.0-alpha.9 for example the validator was updating on every keystroke. 
Now, in v2.0.0-alpha.15 the validator is only updating after input "blur".

I would like to be able to configure the event on which to trigger the validation so for example it can validate the input in real-time or simply configure a small delay using the vue.js `debounce` property http://vuejs.org/guide/forms.html#debounce directly on the input.

I really think that this should be considered a configurable preference, rather than imposing the "blur" behaviour on everyone.

I hope you understand what I mean.

**Comment by kazupon** [comment]
Thanks for your concrete feedback!
I'll try to consider it. :smiley_cat:

**Comment by lazabogdan** [comment]
@kazupon Thank you! How about the model issues? Have you had the chance to look at my fiddle yet?

**Comment by kazupon** [comment]
I'm tracing the source of the problem now.
I feel that this issue (`v-for` and `v-model` using case) is difficult. in this reason, it takes a little time to fix.
:bow: 

If you want to resolve this issue right now, i hope that you will resolve the other way.

**Comment by lazabogdan** [comment]
Thanks for the update! It's good to know the issue is confirmed and that you're working on it. That was all I wanted to know. For now, I'll just use v2.0.0-alpha.9 until the bug is fixed.

**Comment by lazabogdan** [comment]
@kazupon Found something. The issue has something to do with the latest updates on vue.js. Here's an updated fiddle WORKING using Vue.js v1.0.13 and vue-validator v2.0.0-alpha.15 https://jsfiddle.net/lazabogdan/qu1L9pez/

**Comment by lazabogdan** [comment]
Apparently it's working just fine when NOT using the "field" attribute. Also, the validator updates in real time, not on "blur" so it seems my 2nd request is also linked to the main issue. See:

##### Working

https://jsfiddle.net/lazabogdan/og3dvq5s/

##### Not working (using "field")

https://jsfiddle.net/lazabogdan/87seoL35/

**Comment by kazupon** [comment]
Thank you very much !! :smiley_cat: 

I found the strange behavior.
https://jsfiddle.net/kazupon/0evyqncj/7/

In the above jsfiddle example codes, I don't use the `vue-validator`.
`v-validate` is implemented with terminal directive.

I have a spec of terminal directive that I don't know about the behavior of terminal directive.
I'll try to ask the evan.
