### ISSUE TITLE
the wrong behavior when press backspace in v2.0.0-alpha.15

### ISSUE THREAD

**Issue by oliverzy** [kazupon/vue-validator#141]
Hi,

I upgraded from alpha.9 to alpha.15, suddenly my all input control behave wrong when pressing backspace.

Reproduce Steps:
1. Input a few characters
2. Move the cursor to the middle
3. Press backspace, you will see the cursor is mistakenly placed to the end of the input control

**Comment by kazupon** [comment]
Thanks for your reporting!

Can you provide the minimum reproduction codes (jsffidle, codepen, etc ...) please ?

**Comment by kazupon** [comment]
related #142
