### ISSUE TITLE
[Vue warn]: Unknown custom element: <validator> - did you register the component correctly?

### ISSUE THREAD

**Issue by nacr** [kazupon/vue-validator#143]
Hello I'm getting this error,

I cant find the problem any help?

`[Vue warn]: Unknown custom element: <validator> - did you register the component correctly?
app-699e3b8ed5.js:3576 Error: Warning Stack Trace
    at warn (app-699e3b8ed5.js:3576)
    at checkComponentAttr (app-699e3b8ed5.js:4067)
    at checkComponent (app-699e3b8ed5.js:9448)
    at compileElement (app-699e3b8ed5.js:9240)
    at compileNode (app-699e3b8ed5.js:9201)
    at compileNodeList (app-699e3b8ed5.js:9383)
    at compileNodeList (app-699e3b8ed5.js:9384)
    at compileNodeList (app-699e3b8ed5.js:9384)
    at compileNodeList (app-699e3b8ed5.js:9384)
    at compileNodeList (app-699e3b8ed5.js:9384)
app-699e3b8ed5.js:1921 Uncaught TypeError: Vue.parsers.directive.parse is not a function`

**Comment by nacr** [comment]
Can any one help me????

**Comment by kazupon** [comment]
related #124 

vue-valudator 1.x is not working with VueJS 1.x. Use vue-validator 2.x.
https://github.com/vuejs/vue-validator/releases

You can use the below installation
https://github.com/vuejs/vue-validator#development-version

**Comment by nacr** [comment]
tks will give it a go :+1:

**Comment by nacr** [comment]
Tks @kazupon, all is well sorry for the noob question.

**Comment by nicolasbeauvais** [comment]
`npm install --save vuejs/vue-validator#v2.0.0-alpha.20` solved it for me, and it avoid installing all the dev dependencies if you don't need them.

**Comment by steven-klein** [comment]
If you are using vue-router, I found that using vue-validator before the router fixed the issue.

```
var VueValidator = require("vue-validator");
var VueRouter = require("vue-router");

Vue.use( VueValidator );
Vue.use( VueRouter );
```

**Comment by blocklevel-timrijkse** [comment]
I'm trying to npm install vue-validator 2.1.5 with Vue v1.0.26 but I still get the error "Unknown custom element: <validator>".

Any idea? Thanks!

**Comment by carychenyan** [comment]
thanks

**Comment by woshi82** [comment]
i am using  vue-validator v2.1.3  vue  v1.0.16 ,

**Comment by woshi82** [comment]
I'm also got this error, i am using vue-validator v2.1.3 vue v1.0.16 , i have try the ways upfloor,but useless.
`[Vue warn]: Unknown custom element: <validator> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

**Comment by liuyanghe19910609** [comment]
what can I say?
I 'm f*cking by this Qusetion and I don't know what can I do……
So I search on the Bing and find this page^
hehehe^^^^
I don't know what you say……

**Comment by liuyanghe19910609** [comment]
啊……这么说好费劲，而且我本来英语就比较渣渣
直接说问题
validator的包或者说组件我已经安装好了
npm install validator --save-dev
安装好了，但是并没有什么卵用……
重新启动服务然后页面依然报错
说起来这里为什么没法贴图？

**Comment by liuyanghe19910609** [comment]
啊……这么说好费劲，而且我本来英语就比较渣渣
直接说问题
validator的包或者说组件我已经安装好了
npm install validator --save-dev
安装好了，但是并没有什么卵用……
重新启动服务然后页面依然报错
说起来这里为什么没法贴图？

**Comment by abbymrs** [comment]
@steven-klein 
Hi, 
I use vue-router and tried your way, but still not work....
PS: 
```
vue@2.1.8
vue-router@2.1.1
vue-validator@3.0.0-alpha.2
```

**Comment by woshi82** [comment]
@abbymrs hi,the problem went  too long,
the validator component deprecated， https://github.com/kazupon/vue-validator/issues/257

**Comment by abbymrs** [comment]
@woshi82
thanks, i resolved this problem.
I have another problem, when i add vue-validator to my project for form validate, the browser is crashed, i have tried in company also home, all with the same result.... do you have this issue?

**Comment by 6km46793** [comment]
@liuyanghe19910609 佩服佩服。

**Comment by QinFeiFei** [comment]
3.0版本用 <validation>

**Comment by QinFeiFei** [comment]
validation

**Comment by QinFeiFei** [comment]
不是 validator

**Comment by codebdy** [comment]
use <validation> instead of <validator>

**Comment by cheaprYang** [comment]
我擦

**Comment by cheaprYang** [comment]
希望各位看的懂中文
