### ISSUE TITLE
checkbox validation in generated tables

### ISSUE THREAD

**Issue by codylandry** [kazupon/vue-validator#146]
I have a table with multiple checkboxes in each row. The table is generated with v-for directives.  I need to validate that at least one checkbox is selected.  I've tried adding the validator directive with the minlength requirement to each checkbox. This didn't work at all.   I've also tried adding a hidden checkbox with the requirements and then just the validator on the visible checkboxes.  This works somewhat.  The minlength is 1.  When I click one box, valid stays false.  When I click another, it goes true, but when I unclick both, it stays true.  Is this a vue-validator issue or am I doing it wrong?

**Comment by kazupon** [comment]
Thank you for your reporting!

Can you provide the reproduction code (e.g. jsfiddle) please?

**Comment by codylandry** [comment]
I'm having issues with getting vue-validator working at all in the jsfiddle, but here is what I'm trying to do.  I can't reproduce the error in the fiddle, because I can't get Vue to recognize vue-validator.  

https://jsfiddle.net/codylandry/y7ywo72n/11/

I've had the best luck with using the hidden checkbox with the validator 'definition' setup there.  This is how I got the results above.

**Comment by kazupon** [comment]
Thanks for your reproduction code.

I changed the your vue-validator specified with standalone js file to latest version.
https://jsfiddle.net/kazupon/yma52y42/1/

Can you update reproduction setting please ?

**Comment by codylandry** [comment]
Actually, now it’s behaving exactly as in my application.  

Steps:
1. Check 1 box and valid stays false. I would expect valid to become true at this point.
2. Check a second box and valid becomes true.
3. Uncheck both boxes and valid remains true.

Let me know if this still doesn’t make sense.  Ideally, you wouldn’t have to have a hidden checkbox to define the validator options, but if you set the options in any of the dynamic checkboxes, it doesn’t work at all.

**Comment by codylandry** [comment]
This issue seems to have been fixed in the latest release.

https://jsfiddle.net/c5014yhf/

**Comment by kazupon** [comment]
Thanks
