### ISSUE TITLE
minLength and maxLength doesn't work

### ISSUE THREAD

**Issue by Almis90** [kazupon/vue-validator#147]
Here is my code https://jsfiddle.net/217j3m9z/2/

**Comment by kazupon** [comment]
You should not use `minLength` but `minlength`.  :smiley_cat:

**Comment by Almis90** [comment]
Okay please update documentation :)

**Comment by kazupon** [comment]
oh, sorry
I didn't find the mistake document.
Can you tell me the about it ?

**Comment by Almis90** [comment]
Sorry my bad... I was looking at 1.4.4 :/
