### ISSUE TITLE
Manually trigger validations

### ISSUE THREAD

**Issue by Almis90** [kazupon/vue-validator#150]
I have custom validation

```
uniqueUsername: function (val) {
    return !this.usernameExists;
}
```

and a method

```
usernameKeyup: function () {
    var self = this;
    Vue.http.post('/username', { username: this.username }).then(function (res) {
        if (res.data.success) {
            self.usernameExists = res.data.object;
        }
    }).catch(function (res) {
        console.log(res);
    });
}
```

When the usernameExists changes the validation is not re-evaluating, only when I go to next input it shows the correct validation. Is there any way that I could manually re-evaluate for single input?

**Comment by kazupon** [comment]
Currently, vue-validator cannot the re-evaluate for single input manually.
I'll try to consider it. :smiley_cat:

**Comment by Almis90** [comment]
Hey can you explain me please how I can now manually re-evaluate with your latest code change now?

**Comment by kazupon** [comment]
Sorry.
It was not over yet. 

To resolve this issue, We need to improve the vue.js
I push the PullRequest to vuejs/vue repositry, I'm waiting the it.

https://github.com/vuejs/vue/pull/2272
