### ISSUE TITLE
Pass Property to Custom Validator

### ISSUE THREAD

**Issue by nacr** [kazupon/vue-validator#151]
Hello for what I see here:

`Vue.validator('email', function (val) {
    return /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(val)
});`

I can make my custom validator but how can I pass data to it.

Imagine:

`v-validate:passwordConfirm="{  required:true, minlength:8, equal:password }"`

Any ideias?

tks

**Comment by kazupon** [comment]
Sorry, poor documentation.

Your custom validator function, first argument is passed the field value, second argument is passed the rule value has been  specified with `v-validate`.

**Comment by nacr** [comment]
Will check tks :)

**Comment by nacr** [comment]
tks for the info. <3 your work.
