### ISSUE TITLE
async validation example?

### ISSUE THREAD

**Issue by danjac** [kazupon/vue-validator#156]
According to #10 async validation (using promises) was added to vue-validator in 1.4.0. However as of 2.0.0.alpha the README still has async as a TODO item and there is only a stub test and no working examples around.

Could you please confirm a) if async validation is now in vue-validator and b) where we can find an example with the current release version (2.0.0.alpha)?

**Comment by danjac** [comment]
I did find an example here https://github.com/vuejs/vue-validator/wiki/Usage-for-v0.12-later#async-validation but it appears to be out of date with the current release.

**Comment by kazupon** [comment]
Sorry, I don't implement the async validation yet in 2.0.0.alpha, because I'm developing from full scratch.
I'll plan to develop the async validation soon. :smiley_cat:

**Comment by danjac** [comment]
No problem, glad you're working on it.

What do you expect async-validation in 2.0 to look like? The 1.4\* returned a plain function with (resolve, reject) arguments, but perhaps a straightforward Promise would be a more "natural" way of handling async.

**Comment by kazupon** [comment]
I'll support to the Promise and like v1.4\* `function(resolve, reject)`. :smiley_cat:

**Comment by tylersnyder** [comment]
@kazupon any updates as to when you think async validation may be implemented in 2.0?

**Comment by kazupon** [comment]
@tylersnyder 
Please wait  :smiley_cat:
