### ISSUE TITLE
validator with nested componenets

### ISSUE THREAD

**Issue by leemason** [kazupon/vue-validator#160]
i have an app thats currently rendered like this:

```
<validator name="settings">
<settings-page :panels="panels">
<settings-panel :panel="panel">
<div v-for="field in panel">
<setting-field :field="field"></setting-field>
</div>
</settings-panel>
</settings-page>
</validator>
```

this creates the warning: [vue-validator] v-validate need to use into validator element directive: (e.g. <validator name="validator"><input type="text" v-validate:field1="['required']"></validator>).

so i tried passing in the validator instance on each component:

```
<validator name="settings">
<settings-page :panels="panels" :validator="$settings">
<settings-panel :panel="panel" :validator="$settings">
<div v-for="field in panel">
<setting-field :field="field" :validator="$settings"></setting-field>
</div>
</settings-panel>
</settings-page>
</validator>
```

however this still doesnt work? im sure its down to the nested components, but there must be a way to use it without errors this way?

ive read the docs, and can confirm im using :field="field.id" to dynamically set the field reference in the v-for.

**Comment by kazupon** [comment]
related #96

**Comment by kazupon** [comment]
Sorry, In currently version, vue-validator can't use the validator was  defined at parent vm instance.

**Comment by kazupon** [comment]
Close (exist #96)
