### ISSUE TITLE
touched property not true when tabbing

### ISSUE THREAD

**Issue by MrOggy85** [kazupon/vue-validator#163]
Hi,

I am using a field property to determine if I should show an error message or not. I found it wise to use the "touched" property of the field for this task. It works great when you have focused the field and then used the mouse to focus on another field. However it doesn't have the same behavior if I simply change field using the tab character.

EDIT:
This is only the case when tabbing from an input field to a button. If I tab to another input field the property is changed.

**Comment by jakejscott** [comment]
I'm having the same issue, when I tab from the first field in the form touched changes to true, but when I tab from subsequent fields the touched property doesn't change.
