### ISSUE TITLE
Custom validator with twoway filter changing value displayed in textbox

### ISSUE THREAD

**Issue by codylandry** [kazupon/vue-validator#167]
I'm having an issue where when I apply a custom validator and a custom twoway filter, the value that appears in the textbox changes.  The data in the model is correct, but the value in the textbox is wrong.  I can't seem to reproduce this in a jsfiddle, but I can give you pieces of my code.

Here is the custom validator.  PhoneNumber is from an npm package called awesome-phonenumber
![image](https://cloud.githubusercontent.com/assets/12991706/13672623/a3938162-e6a3-11e5-8f8a-9b5fb61de551.png)  I've added it in the example file in comments.

The problem comes when you toggle the element with v-if.  When you hide it, and then show it again, the value in the textbox is wrong and the valid state goes false.

I hope this is enough to help you find the problem.  Let me know if you need more clarification. Thanks.  Love vue-validator.

before input:
![image](https://cloud.githubusercontent.com/assets/12991706/13673747/7d5633fa-e6a8-11e5-8490-15e183a50337.png)

with valid input:
![image](https://cloud.githubusercontent.com/assets/12991706/13673650/134f8d94-e6a8-11e5-9626-c24c115f7b1f.png)

after toggling v-if:
![image](https://cloud.githubusercontent.com/assets/12991706/13673666/2776a53c-e6a8-11e5-98b6-96a06f849353.png)

after toggling v-if again:
![image](https://cloud.githubusercontent.com/assets/12991706/13673777/9a62fcc6-e6a8-11e5-9e03-ec5d9d0a3517.png)

```
<template>
    <div>
        <validator name="phone">
            <button @click="show = !show">toggle</button>
        <input v-model="testPhone | phoneNumber"
               class="form-control"
               @click.stop=""
               name="editPhone"
               v-validate:edit-phone="{phone: 'US'}" v-if="show">
            <br>
            data:
            <pre>[[$data | json]]</pre>
            validation:
            <pre>[[$phone | json]]</pre>
        </validator>
    </div>
</template>



<script>

//Vue.validator('phone', {
//  message: 'invalid phone number', // error message with plain string
//  check: function (val, countryCode) { // define validator
//    if (!val) return false
//      return PhoneNumber(val, countryCode).isValid()
//  }
//})


    import PhoneNumber from 'awesome-phonenumber'
    export default{
        data(){
            return {
                testPhone: '',
                show: true
            }
        },
        filters: {
            phoneNumber: {
                read: function (val) {
                    console.log(val)
                    if (typeof val === 'undefined') {
                        return ''
                    }
                    let pn = new PhoneNumber(val, 'US')
                    console.log(pn)
                    console.log(pn.getNumber('national'))
                    return pn.getNumber('national')
                },
                write: function (val) {
                    let pn = new PhoneNumber(val, 'US')
                    return pn.getNumber('significant')
                }
            }
        }
    }
</script>

<style>
    body {
        background-color: #FFF;
    }
</style>
```

**Comment by kazupon** [comment]
@codylandry 
Thank you for your reporting !!
Sorry for the late response. 

I checked the this issues.
http://jsfiddle.net/kazupon/po0zsgxr/5/

I'll try to fix. :smile_cat:

**Comment by codylandry** [comment]
I tried to test the fix by replacing vue-validator in the jsfiddle and it still behaves the same.  After toggling the v-if back on, nothing is displayed in the textbox.

http://jsfiddle.net/cobby4h3/1/

**Comment by kazupon** [comment]
> http://jsfiddle.net/cobby4h3/1/

I think that jsdelivr is strange ...
https://cdn.jsdelivr.net/vue.validator/2.0.0-beta.2/vue-validator.min.js

I hosted 2.0.0.beta.2 with dropbox.
http://jsfiddle.net/kazupon/xkvs4gnv/3/

In the above jsfiddle, it works.

**Comment by codylandry** [comment]
Awesome. Thanks for the fast response!
