### ISSUE TITLE
camelCase validation names don't work

### ISSUE THREAD

**Issue by chrisbarry** [kazupon/vue-validator#168]
I tried to use this:

v-validate:firstName="['required']"

And it didn't work, but when I switched it to

v-validate:firstname="['required']"

It was fine?

**Comment by codylandry** [comment]
thats backwards actually.  you need to use:

v-validate:first-name="['required']"

and reference it with $yourValidatorName.firstName

**Comment by chrisbarry** [comment]
Ah, ye old kebab to camelcase conversion. Noted.
