### ISSUE TITLE
Not working with select boxes [jsfiddle attached]

### ISSUE THREAD

**Issue by thatandyrose** [kazupon/vue-validator#169]
Can't seem to get the validator to register a required validation with selectboxes.

You can view the bug in the referenced jsfiddle. It work with a text box, but not a select?: https://fiddle.jshell.net/1qd8u5Lk/

**Comment by kazupon** [comment]
You need to set `<option value="">--- select --></option>`.

**Comment by thatandyrose** [comment]
@kazupon hmm but sometimes we don't want an empty value? I think the validator should know that nothing is selected by seeing that there are no selected options?

This sounds like a bug to me no @kazupon? Could you point me to the bit of code that looks for this, maybe I can issue a PR?

**Comment by kazupon** [comment]
> I think the validator should know that nothing is selected by seeing that there are no selected options?

I want to know that use-cases.
Can you provide with the example code please ?

> Could you point me to the bit of code that looks for this, maybe I can issue a PR?

Yes, You can push the PR. I'll be anytime waiting for your PR. :)

**Comment by kazupon** [comment]
Close (in-activity)
