### ISSUE TITLE
2.0.0-beta.2  validators this point $validation

### ISSUE THREAD

**Issue by taoche** [kazupon/vue-validator#170]
version -> 2.0.0-beta.2

in example timing project

```
 validators: {
   confirm: function (val) {
     console.log(this.password)  ->  'undefined' and here this point $validation
     return this.password === val
   }
 },
```

**Comment by kazupon** [comment]
ah, sorry ...

You can use the exposed vue instance.
https://github.com/vuejs/vue-validator#vm-property

**Comment by taoche** [comment]
I know this solution,  but I want to the future will solve this problem it ?

**Comment by kazupon** [comment]
In the beta version later,  validation function context is not vue instance, but validation instance.

I think that this breaking change is not problem, because it's possible with `vm` property and `el` property exposed by vue-validator.

**Comment by taoche** [comment]
Thank you for your answer
