### ISSUE TITLE
placeholder of textarea becomes its value inside validator directive in IE10 and 11

### ISSUE THREAD

**Issue by kenchan0130** [kazupon/vue-validator#172]
Hi,
### vue & vue-validator version

1.0.17, 2.0.0-beta.2
### Steps to reproduce

``` html
<validator>
  <form novalidate>
    <textarea v-validate:comment="{  maxlength: 100 }" placeholder="this is placeholder"></textarea>
  </form>
</validator>
```
### What is Expected?

I expect not to set placeholder value to value of textarea.
### What is actually happening?

When we see this page in IE 10 or IE 11,
set placeholder value to value of textarea.
### Cause

Perhaps it seems that [this](https://github.com/vuejs/vue-validator/blob/33a33783a54c9627e0f63a86958442185d97d36a/src/directives/validator.js#L85) is the cause

In this case,

```
<textarea v-validate:comment="{  maxlength: 100 }" placeholder="this is placeholder">this is placeholder</textarea>
```

by `innerHTML`.
### See also

https://github.com/vuejs/vue/issues/558

**Comment by kenchan0130** [comment]
Hi, @kazupon 
It works now, thanks!

**Comment by trevorgehman** [comment]
@kazupon Has this issue come back in 2.0.2? I had to revert to 2.0.0 because textareas in IE10/11 were messing up again with placeholders.

**Comment by kazupon** [comment]
@trevorgehman 
Hi !
I could not confirm this issue at the below jsfiddle, in IE10/11.
http://jsfiddle.net/kazupon/bbv0bmtw/3/

Can you provide the reproduction code with jsfiddle (or other) please?
