### ISSUE TITLE
Dynamic setting field,how to show Error messages ?

### ISSUE THREAD

**Issue by littleyan-xu** [kazupon/vue-validator#173]
vue-validator version: 2.0.0-beta.3

code:

```
<validator name="validation">
  <form novalidate>
    <div v-for="n in count">
      <input type="number" v-model="startTimes[n]"  field="starttime{{n}}"  v-validate="['required']">
     <span class="error-tips" v-show="$validation[starttime{{n}}].touched && $validation[starttime{{n}}].required">require start time!</span>
    </div>
  </form>
`</validator>`
```

set  "v-show" attribute for Error message  like this is wrong，so what the right answer ?

**Comment by kazupon** [comment]
Can you provide the reproduction codes with jsfiddle(or other) please ?

**Comment by littleyan-xu** [comment]
https://jsfiddle.net/xxyzjb/p4j95xhc/

> [Vue warn]: v-show="$validation[itemval{{n}}].touched && $validation[itemval{{n}}].required": attribute interpolation is not allowed in Vue.js directives and special attributes.

when running this code,the console shows the warning above, so I want to know how to show error message correctly in this situation ?

**Comment by kazupon** [comment]
You need to change `field` to `:field`, and wrap the `n` value with method.

See
http://jsfiddle.net/kazupon/v0gk43m4/2/

**Comment by kazupon** [comment]
Sorry, The documentation is bad example ... :disappointed: 
I'll try to fix. :smiley_cat: 
https://github.com/vuejs/vue-validator#attribute

**Comment by littleyan-xu** [comment]
Thank you very much~!
