### ISSUE TITLE
is it possible to dynamically set validators?

### ISSUE THREAD

**Issue by codylandry** [kazupon/vue-validator#174]
I need to dynamically set validation on fields base on a property in their objects.  

```
<div v-for="item in items">
    <input v-model="item.value"
               field="item{{$index}}"
               v-validate="{required: item.required}"> <!-- I've also tried required: false-->
</div> 
```

No matter what, the required validator gets applied.  Is there a way to dynamically set validators?

**Comment by kazupon** [comment]
Related #173 

Sorry, README.md is bad documentation ...  :disappointed: 

Maybe, you need to change `field` to `:field`, and wrap the `$index` with method.

See:
http://jsfiddle.net/kazupon/v0gk43m4/2/

**Comment by kazupon** [comment]
Close (non-activity)
