### ISSUE TITLE
Validation is called for all fields in form every time

### ISSUE THREAD

**Issue by pavgra** [kazupon/vue-validator#179]
I am confused whether it is OK that validation is called for all fields every time I change something in a form. Check the [fiddle](https://jsfiddle.net/ekfh68gj/) and try to change only 'First name' field. Every time you change it, the 'Second name' field is validated too. Is it OK? For both logic and performance reasons.

Probably this happens because of that in this function

```
BaseValidation.prototype.handleValidate = function handleValidate(el, type) {
      this.willUpdateTouched(el, type);
      this.willUpdateDirty(el);
      this.willUpdateModified(el);

      this._validator.validate(this.field);
};
```

param passed to `this._validator.validate` is `this.field` but not `{field: this.field}`

**Comment by blocka** [comment]
What happens if you have a field A that depends on the value of B? If field B gets updated, I would want the validation to rerun on field A.
