### ISSUE TITLE
"Uncaught RangeError: Maximum call stack size exceeded", even the demo

### ISSUE THREAD

**Issue by hq5544** [kazupon/vue-validator#180]
"vue": "^1.0.18"
"vue-validator": "^2.0.0-beta.6"

This is my first time use vue-validator.
I coped the document demo.
But chrome says "Uncaught RangeError: Maximum call stack size exceeded".

``` js
import VueValidator from 'vue-validator'
Vue.use(VueValidator)
```

``` html
<div id="app">
        <validator name="validation1">
            <form novalidate>
               <div class="username-field">
                    <label for="username">username:</label>
                    <input id="username" type="text" v-validate:username="['required']">
                </div>
                <div class="comment-field">
                    <label for="comment">comment:</label>
                    <input id="comment" type="text" v-validate:comment="{ maxlength: 256 }">
                </div>
                <div class="errors">
                    <p v-if="$validation1.username.required">Required your name.</p>
                    <p v-if="$validation1.comment.maxlength">Your comment is too long.</p>
                </div>
                <input type="submit" value="send" v-if="$validation1.valid">
            </form>
        </validator>
 </div>
```

**Comment by kazupon** [comment]
Please upgrade the vue.js version to 1.0.20

See details:
https://github.com/vuejs/vue/issues/2563

**Comment by hq5544** [comment]
@kazupon Thanks!

**Comment by abbymrs** [comment]
@hq5544 hi, i have the same issue, and i use vue 2.1.8, and i did not mount the app to body, but div element. below is my code:

> main.js

```
import Vue from 'vue';
import App from './App';

new Vue({
    el: '.container',
    render: h=>h(App)
});
```

> App.vue

```
<template>
    <div id="app">
        <h1>hello world</h1>
        <home></home>
        <login></login>
    </div>
</template>
<script>
    import Home from './components/Home';
    import Login from './components/Login'

    export default {
        components: {
            Home,
            Login
        }
    }
</script>
```

**Comment by lewiscutey** [comment]
Uncaught RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at RegExp.[Symbol.match] (<anonymous>)
    at String.match (native)
    at compileToFunctions (http://127.0.0.1:8080/node_modules/vue/dist/vue.js:9021:28)
    at VueComponent.Vue$3.$mount (http://127.0.0.1:8080/node_modules/vue/dist/vue.js:9282:19)
    at init (http://127.0.0.1:8080/node_modules/vue/dist/vue.js:2934:15)
    at createComponent (http://127.0.0.1:8080/node_modules/vue/dist/vue.js:4653:11)
    at createElm (http://127.0.0.1:8080/node_modules/vue/dist/vue.js:4596:11)
    at VueComponent.patch [as __patch__] (http://127.0.0.1:8080/node_modules/vue/dist/vue.js:5052:9)
    at VueComponent.Vue._update (http://127.0.0.1:8080/node_modules/vue/dist/vue.js:2042:21)
