### ISSUE TITLE
Automatic class insertion

### ISSUE THREAD

**Issue by franciscolourenco** [kazupon/vue-validator#182]
https://github.com/aristidesfl/vue-validator already supports this, unfortunately this validator is incompatible with the last release and is not actively maintained.

Original request: https://github.com/vuejs/vue-validator/issues/41#issuecomment-137255577

**Comment by kazupon** [comment]
I support this feature at v2.1.0
https://github.com/vuejs/vue-validator/releases/tag/v2.1.0

docs:
http://vuejs.github.io/vue-validator/en/classes.html
