### ISSUE TITLE
Validator becomes null when modifying a components property.

### ISSUE THREAD

**Issue by Gouvi** [kazupon/vue-validator#189]
Here is the jsFiddle before trying to explain it too much: http://jsfiddle.net/trmdb700/8/

To replicate the issue:
1) Open modal
2) Close the modal with the cross
3) Open the modal again
4) Try submit any content in the input field
5) You will receive "Uncaught TypeError: Cannot read property 'valid' of null"

Somehow the validator is getting dropped? Should I be approaching the validation a different way?

**Comment by kazupon** [comment]
In this case, validator name `event` is conflicted with [scope name](https://github.com/vuejs/vue/blob/be7339b38ad5083fd0d0baaa2eb9f508b5f9ce23/src/directive.js#L237)

I recommend that you are to be named other validator name (e.g. `validator1`).
