### ISSUE TITLE
when use "lazy" attr

### ISSUE THREAD

**Issue by kazaff** [kazupon/vue-validator#194]
``` html
<validator name="blockBoxValidator" lazy>
```

look, when i add "lazy", i will get this message:

```
[vue-validator] validator element directive need to specify 'name' param attribute: (e.g. <validator name="validator1">...</validator>)
```

why?

**Comment by kazupon** [comment]
Thank you for your reporting!!
I could not confirm this issue.

Can you provide the reproduction with jsfiddle or other please ?

**Comment by kazaff** [comment]
sorry, i know y!

when i add "lazy", and my component do not call `this.$activateValidator()` method, this message will show~

so, if i create a normal component( not dynamic),  it only have "ready" hook, do not have "activate" callback, then `this.$activateValidator()` method do not be call. 

thanks ~~
