### ISSUE TITLE
Multiple forms validation ?

### ISSUE THREAD

**Issue by dennyshu** [kazupon/vue-validator#199]
firstly, i am sorry if anyone have asked this question. i have explored issues page and i don't think that i have found the answer.

anyway, i want to create todo list with edit form using vue and vue validator for **each** todo list item which has to be a form for each todo list item, **i generated these items using vue directly from database**, each todo list item form have name (e.g. eat a breakfast), note (e.g. fried rice) input.

my question is; how do i validate each forms ? as i know vue validator have validation1, i have tried to change the '1' with unique IDs but it doesn't seems work. is there any way to 'differenciate' each validator tags ?
any response would be appreciated. many thanks !

here's my code :

```
<validator name="validation1">
   <div class="todo-list-edit-form ">
        <form novalidate>
             <div class="row ">
                 <div v-for="error in $validation1.errors">
                   <small class="text-danger" style="display: block;">@{{error.message}}</small>
                  </div>
                   <div class="form-group col-md-6">
                   <label for="name">Name</label>
                   <input type="text" class="form-control" id="name@{{itum.id}}" placeholder="Name" value="@{{ itum.name }}" v-validate:name="{
                   required: { rule: true, message: 'Must be filled.' },
                   pattern: { rule: '/^[A-Za-z0-9\s,.!?\']+$/u', message: 'Must be valid.' }
                   }">
               </div>
              </div>
          <div class="row">
           <div class="form-group col-md-6">
               <label for="note">Note</label>
                <input type="text" class="form-control" id="note" placeholder="Note" value="@{{ itum.note }}">
                </div>
              <div class="form-group col-md-5">
              <button class="btn btn-primary todo-list-edit-form-button" v-on:click="updateTodoList(itum.id)">Save To-Do List</button>
               </div>
              <div class="form-group col-md-1">
                     &nbsp;
       </div>
      </div>
</form>
   </div>
 </validator>
```

**Comment by kazupon** [comment]
I think that you can use the below code:

``` html
<ul>
  <li v-for="item in items">
    <validator name="validation{{$index}}">
    ...
    </validator>
  </li>
</ul>
```

**Comment by dennyshu** [comment]
thank you for your response !

but, what if i want that $index in my validation[number] variable ? 
for example :

```
<div v-for="error in $validation1**(< this one)**.errors">
    <small class="text-danger" style="display: block;">@{{error.message}}</small>
</div>
```

**Comment by kazupon** [comment]
I think that you can use the below code:

``` html
<div v-for="error in getValidationErrors($index)">
    <small class="text-danger" style="display: block;">@{{error.message}}</small>
</div>
```

``` js
new Vue({
  ...
  methods: {
    getValidationErrors: function (index) {
      return this['$validation' + index].errors
    }
  },
  ...
})
```

jsfiddle:
http://jsfiddle.net/kazupon/9zp56d8h/1/

**Comment by dennyshu** [comment]
hello, thanks again for the response !

i got this error : 
[Vue warn]: Error when evaluating expression "getValidationErrors(itum.id)". Turn on debug mode to see stack trace.

seems like the $validation[index] variables are still 'empty', when i do {{$validation1|json}}, nothing appearred.

here is my modified code..

view :

```
<validator name="validation@{{itum.id}}">
     <div class="todo-list-edit-form hide" >
       <form novalidate>
             <div class="row ">
                  <div v-for="error in getValidationErrors(itum.id)">
                       <small class="text-danger" style="display: block;">@{{error.message}}</small>
                   </div>
               </div>
      </form>
      </div>
</validator>
```

vue :

```
getValidationErrors: function (index) {
      return this['$validation' + index].errors;
}
```

**Comment by kazupon** [comment]
I seem that your example code is incorrect.
- bad

``` html
<validator name="validation@{{itum.id}}">
```
- good

``` html
<validator name="validation{{itum.id}}">
```

**Comment by dennyshu** [comment]
i think that is not the problem, because i have tested in my script like this :

```
div class="todo-list-edit-form hide@{{itum.id}}" >
```

and then, i do inspect element and shows me this :

`<div class="todo-list-edit-form hide1" >`

same as the actual value of @{{itum.id}}

**Comment by kazupon** [comment]
hmm...
Can you provide the minimum reproduction codes with jsfiddle (or jsbin, etc) please ?

**Comment by dennyshu** [comment]
here's the jsfiddle:

https://jsfiddle.net/haisenberg/z2t2ztq2/

note: in laravel blade template, we use @ to indicate the javascript variables
for example :
<div class="todo-list-edit-form hide@{{itum.id}}" >
is equally as :
<div class="todo-list-edit-form hide1" >

**Comment by kazupon** [comment]
Thank you for reproduction code providing !!

I think that you can avoid with the below code
https://jsfiddle.net/kazupon/z2t2ztq2/1/

**Comment by dennyshu** [comment]
thanks, it's working now !

arigatou gozaimasu !

**Comment by kazupon** [comment]
Enjoy vue.js 😺

**Comment by dennyshu** [comment]
i am sorry @kazupon, but i have another problem now, XD

after i clicked 'save button' of the form, the validator doesn't work again and when i run {{$validation1|json}} it says 'null' on the view.

here is my code when button clicked :

```
updateTodoList:function(tlid,e){
            e.preventDefault();
            this.form_data.tlid = tlid;
            this.form_data.name = $('#name'+tlid).val();
            this.form_data.due_date = $('#datetimepicker'+tlid).val();
            this.form_data.note = $('#note'+tlid).val();

            this.$http.post(settings.base_url+'/user/api/updateTodoList',this.form_data, function(data){

                this.todo_list_months = data.user_event_due_date_months;

                this.$nextTick(function () {
                          // can this do anything ?
                    });
                })
            }).error(function(response){

            });
        },
```

**Comment by kazupon** [comment]
sorry, i could not understand your code ...
can you provide the minimum reproduction code please?

**Comment by dennyshu** [comment]
i'm sorry, i was sleepy last night lol.

here is my jsfiddle, edited from last time :

https://jsfiddle.net/haisenberg/u3z4ocgo/

so, i want to update the todo list data and re-load the data after the update, but the validator seems not working again.

**Comment by kazupon** [comment]
You can avoid with the below
https://jsfiddle.net/kazupon/1zLpwbju/1/

**Comment by dennyshu** [comment]
i have got that worked, this is another issue. 
after i press the Save to-do list button (updateTodoList event), and reload the data :
this.this_months_todo_lists = data.this_months_todo_lists;

the validation seems not working anymore, is there any way to update and reload the data afterward in vue.js ?

**Comment by morganzysman** [comment]
Hello,
I seem to have the same problem, I always get
`[Vue warn]: Error when evaluating expression "getValidationErrors($index).errors": TypeError: Cannot read property 'errors' of undefined`

I'm using a similar code as the one you gave in the jsfiddle.

Thank you
