### ISSUE TITLE
vue-validator, webpack - no errors but not working

### ISSUE THREAD

**Issue by murbanowicz** [kazupon/vue-validator#212]
Hi,

I am confused what's going on.
I have no errors in console but vue-validation is not working at all.
I am using webpack in my project.

Here is `main.js` :

```
import Vue from 'vue'
import ep_panel from './ep_panel'

Vue.use(require('vue-resource'));
Vue.use(require('vue-validator'));

/* eslint-disable no-new */
new Vue({
  el: 'body',
  components: { ep_panel }
});
```

In my component I have:

```
<validator name="eventVal">
    <form novalidate>
    </form>
   <pre>{{ $eventVal | json }}</pre>
</validator>
```

Anything else inside is just form.
I tried to put v-validate but after having no success and `v-if="$eventVal.valid"` is totally not working,
I removed everything to just check if anything is working with vue-validator.

I am getting empty `<pre></pre>` in browser and I have no idea why.

Should validator be visible in VueDevtools or not? It's not now.
vue-validator ver. 2
I will appreciate your help.

**Comment by kazupon** [comment]
> Should validator be visible in VueDevtools or not? It's not now.

validator don't integrate vue-devtools.

> I tried to put v-validate but after having no success and v-if="$eventVal.valid" is totally not working,
> I removed everything to just check if anything is working with vue-validator.

Can you provide the minimum codes please?

**Comment by murbanowicz** [comment]
> Can you provide the minimum codes please?

@kazupon what you want exactly? I've provided all relavant code. What else you need? I am really confused why it is still not working.

**Comment by kazupon** [comment]
Sorry, In my enviroment, I tried to   reproduce, but I could not confirmed.
I hope that you provide the reproduction info (minimum codes, error call stacks,etc ...) to me.

**Comment by murbanowicz** [comment]
I can even send you whole project if you want? Any email ?

2016-05-05 16:28 GMT+01:00 kazuya kawaguchi notifications@github.com:

**Comment by kazupon** [comment]
> I can even send you whole project if you want? Any email ?

I hope that provide web code sharing tool ([jsfiddle](https://jsfiddle.net), [webpackbin](http://www.webpackbin.com), etc)

**Comment by murbanowicz** [comment]
It is my duty to clarify it: I had attached vue.js inside my html template when I already have it compiled within my webpack built file and it was causing this issue. sorry!

**Comment by kazupon** [comment]
That's okay 😺
