### ISSUE TITLE
validator-error component doesn't work

### ISSUE THREAD

**Issue by sqal** [kazupon/vue-validator#214]
### vue & vue-validator version

1.0.21, 2.1.0
### Reproduction Link

http://www.webpackbin.com/EkcnXHe-W
### Steps to reproduce

Just click verify button
### What is Expected?

validator-errors component should render list of errors
### What is actually happening?

Nothing is happening. Component doesn't show any messages (A commented example using v-if works fine though.). In addition when you type something into the input and click verify, input value is truncated to 2 characters and can't be removed from the input. 

Console.log:
`Uncaught TypeError: Cannot read property 'type' of null`

**Comment by sqal** [comment]
Thank you for fixing the issue quickly @kazupon. Btw now i realized that i forgot about proper rule syntax `required: { rule: true, message: 'smth' }` that's way validator  didn't show any errors :D sorry for that, I'll be more careful next time. Have a nice day.

**Comment by frangeris** [comment]
I'm trying to use it too but is not rendering the list of errors, it should output the list of errors, using:
`"vue": "^1.0.21",`
`"vue-validator": "^2.1.1"`

Reproduction link....
[https://jsfiddle.net/8eg5c0sm/1/](https://jsfiddle.net/8eg5c0sm/1/)

**Comment by kazupon** [comment]
@frangeris 
You need to specify the error message of `reuiqred` with `v-validate` directive
https://jsfiddle.net/kazupon/qLvb2ob3/1/
