### ISSUE TITLE
Can't hide errors after clearing v-model

### ISSUE THREAD

**Issue by sqal** [kazupon/vue-validator#215]
Example of my issue: http://www.webpackbin.com/EJqibhGZb After submitting the form i would like to clear all form fields and hide all errors as well, but this is not happening as you can see. How can I solve this?

vue@1.0.21, vue-validator@2.1.1

**Comment by kazupon** [comment]
You can avoid this issue with `initial` attribute and `setValidationErrors` meta method.
http://jsfiddle.net/kazupon/3yLk0drr/4/

reference:
- `initial` attribute
  http://vuejs.github.io/vue-validator/en/timing.html
- `setValidationErrors` meta method
  http://vuejs.github.io/vue-validator/en/api.html

**Comment by ryanwangtian** [comment]
@kazupon 
setValidationErrors can only clear the error message but not the 'invalid' class on the element. is there another way to solve this?

**Comment by sqal** [comment]
@kazupon your solution doesn't work as I expect. After submitting the form I want to clear input model, but when i do that, the errors are back again - http://jsfiddle.net/3yLk0drr/6/ Maybe there should built-in function to do such a thing? `$clearErrors()` ?

**Comment by kazupon** [comment]
Hmm, we need to improve the manually validation. I'll try to improve it.

**Comment by nblackburn** [comment]
Got the same issue, hopefully this can be resolved soon.

**Comment by kazupon** [comment]
I'll try to implement at v3.0.

**Comment by kazupon** [comment]
released v3.0.0-alpha.1
https://github.com/vuejs/vue-validator/releases/tag/v3.0.0-alpha.1

In 3.0 later, validation is default manually.
we can avoid  with using `validate` and `reset` methods.
