### ISSUE TITLE
{ required : false } doesnt work

### ISSUE THREAD

**Issue by StefanNeuser** [kazupon/vue-validator#217]
If you set required to false the validator checks also if value is required and set error

**Comment by kazupon** [comment]
Thank you for your feedback.

This is the spec.
`required` don't need **rule**.

See:
http://vuejs.github.io/vue-validator/en/syntax.html

**Comment by StefanNeuser** [comment]
Hi thanks for your reply. 

Ok, but what happens when i want to switch the required within a config from true to false. Required or not Required?

**Comment by kazupon** [comment]
if you set the `false` to `reuiqred` rule, it is the same as behavior when set the `true`.
if you need to  expect the behavior when set the `false`, I recommend that you don't use the `required` validator.

**Comment by StefanNeuser** [comment]
ok, thx :)

**Comment by szkrd** [comment]
@stefan-neuser How did you programmatically change the 'required' property? I delete it from my rules, but it doesn't seem to be working.

I even tried it with mutated/flushed array with 'required'
https://jsfiddle.net/szabi/hv77xjus/

@kazupon is it possible to change required dynamically?

**Comment by Saymon-biz** [comment]
Also looking for this! I also need toggle required dynamically.

**Comment by nandin-borjigin** [comment]
A workaround, but not neat. [jsfiddle](https://jsfiddle.net/Nandiin/hv77xjus/1/)

**Comment by jackPanyj** [comment]
@Nandiin 

i find that when i use v-if not v-else it doesn't work

[jsfiddle](https://jsfiddle.net/panshao/k9mfum12/2/)

**Comment by nandin-borjigin** [comment]
@jackPanyj 
Yeah, I don't know why, but the solution is assigning different validator field name to each branch, like [updated jsfiddle](https://jsfiddle.net/Nandiin/k9mfum12/3/). Note that the first validator's field name is input1 while the second one is input2

**Comment by szkrd** [comment]
I do know about the v-if workaround, but with 10+ fields this is  a no go (especially if the ui needs to show a "readonlyish" fake field). I could "fix" it with async/promise validators, but that's another terrible hack. At least I can get away with no fake inputs or if switchers.
