### ISSUE TITLE
Uncaught TypeError: t.elementDirective is not a function

### ISSUE THREAD

**Issue by zwl1619** [kazupon/vue-validator#218]
I am using vue 2.0 and vue-validator 2.1.1,There is an error belonging to vue-validator:

```
Uncaught TypeError: t.elementDirective is not a function
```

`elementDirective` was deprecated in vue 2.0.
Is this the resason?

**Comment by kazupon** [comment]
vue 2.0 is still pre-alpha.
vue-validator cannot support as well as other plugin (vue-router,  etc ...)
please use the vue 1.x

**Comment by nekman** [comment]
Any updates here? Vue 2.0 is now v2.0.0-rc.6.

**Comment by nblackburn** [comment]
Getting this error on the latest release client with everything updated, any updates?

**Comment by dfk7677** [comment]
`Uncaught TypeError: Vue.elementDirective is not a function`
Vue 2.0.1

**Comment by asolopovas** [comment]
same here

**Comment by v-petukhov** [comment]
@asolopovas @dfk7677 Guys, vue-validator ver.2 doesn't support Vue 2.0. If you your project uses Vue-Validator, you can't upgrade Vue to the second version, until @kazupon will not release vue-validator ver.3

**Comment by astroanu** [comment]
what's the max vue version that works with vue-validator ?

**Comment by nblackburn** [comment]
@astroanu The latest 1.x release
