### ISSUE TITLE
Top level validation events do not work with vue@1.0.22 and higher

### ISSUE THREAD

**Issue by karol-f** [kazupon/vue-validator#233]
### vue & vue-validator version

1.0.22, 2.1.1
### Reproduction Link

https://jsfiddle.net/tzj8kjc9/
### Steps to reproduce

Top level validation events don't work with vue@1.0.22. Try to change Vue version to e.g. 1.0.21 and you will see that it works.
Example is from https://github.com/vuejs/vue-validator/blob/dev/example/event/top/index.html
### What is Expected?

Top level validation events works.
### What is actually happening?

Top level validation events don't work.

**Comment by blocka** [comment]
Ran into this today as well. For some reason, it was being evaluated as a statement expression, so I had to do `@valid="onValid()"`

**Comment by aaronjpitts** [comment]
I also have this issue.

**Comment by karol-f** [comment]
Thank you!

**Comment by kazupon** [comment]
release v2.1.2
please try it!
https://github.com/vuejs/vue-validator/releases/tag/v2.1.2
