### ISSUE TITLE
when I use my own validator, detect-change="off" doesn't work

### ISSUE THREAD

**Issue by zachzhao1984** [kazupon/vue-validator#235]
I define my validator like this: 

> `Vue.validator('IDNumber', function (val) {
>     return Validator.isValid(val);
>   });`
> 
> `<input type="text" initial="off" v-model="race_registration.certificate_number" initial="off" detect-change="off" detect-blur="on" v-validate:certificate_number="['IDNumber']" v-on:blur="autocomplete($event)"  placeholder="请输入证件号码">`

but validator keep detecting changes

**Comment by kazupon** [comment]
Thank you for your reporting!!

I tried confirmed, however I could not  reproduce the your reporting behavior.
https://jsfiddle.net/kazupon/gcq3dugq/6/

Can you provided the minimum reproduction codes with jsfiddle or jsbin please ?

**Comment by kazupon** [comment]
In-activity
