### ISSUE TITLE
Async select validation

### ISSUE THREAD

**Issue by erguotou520** [kazupon/vue-validator#237]
### vue & vue-validator version

vue: 1.0.24
vue-validator: 2.1.1
### Reproduction Link

https://jsfiddle.net/nkccqdy7/
### What is Expected?

`$validation.foo.required` to be `false`
### What is actually happening?

`$validation.foo.required` to be `true`

**Comment by kazupon** [comment]
Thank you for your reporting!!

I found your mistake.

``` js
setTimeout(function() {
  this.foo = '2'; // `this` context is "function"
 }, 500);
```

**Comment by erguotou520** [comment]
Sorry for mistake, updated.
https://jsfiddle.net/nkccqdy7/1/

**Comment by kazupon** [comment]
one more thing, I found the your mistake about validation rule.

please, see the below:
https://jsfiddle.net/kazupon/0qbxysyh/3/

**Comment by erguotou520** [comment]
Yes, I know it, so in the demo #238 fixed.
