### ISSUE TITLE
Directives that change the DOM

### ISSUE THREAD

**Issue by blocka** [kazupon/vue-validator#242]
### vue & vue-validator version

1.0.24, 2.1.1
### Reproduction Link

If really necessary will, provide, but am limited in time.
### Steps to reproduce

Add a validator on to an element that changes the elements DOM...either by wrapping it or adding to it.
### What is Expected?

The validator will use the intended form element (`this.el`)
### What is actually happening?

The validator is using the fragment instance, which is modified by directive. Since this is a terminal directive, the priority does not seem to make a difference....custom directive is always called first. This results in all sorts of bugs.

**Comment by kazupon** [comment]
Thank you for your feedback.
Sorry, I could understand your explanation.

If you can reproduce this issue, Can you provide the reproduction code please?

**Comment by blocka** [comment]
I think it was fixed here #243
