### ISSUE TITLE
$validation.shortTitle.errors is undefined if I don't set a message for each rule

### ISSUE THREAD

**Issue by felixpy** [kazupon/vue-validator#245]
Here is the html:

```
<div class="form-group control-group">
    <label class="col-xs-1 control-label" for="shortTitle">shortTitle：</label>
    <div class="col-xs-5 controls">
        <input v-model="param.shortTitle" v-validate:short-title="{maxlength:12}" type="text" class="form-control" name="shortTitle">
        <div v-if="$validation.shortTitle.maxlength"><span class="validator-error">Short title is too long</span></div>
    </div>
</div>
```

Only when I changed the v-validate derective to `v-validate:short-title="{maxlength:{rule:12,message:'Too long'}}"` can I get the "errors" array.  So how can I fix this? Thanks.

**Comment by kazupon** [comment]
Thank you for your reporting!
I tried to reproduce this issue, but I could not.
Can you provide the minimum reproduction example code with jsfiddle(or jsbin, codepen...etc) please?

**Comment by felixpy** [comment]
Sorry for the late response.
Here is the example: [jsfiddle](https://jsfiddle.net/felixpy/z6h7js1w/)
I think "errors" array should list all errors even without specified message.
BTW, is there a way to add default message for those rules already in vue-validator(required, maxlength, etc.)?

**Comment by kazupon** [comment]
Sorry for late response.
I checked the your jsfiddle code.
This is the expectable behavior of vue-validator.

.>BTW, is there a way to add default message for those rules already in vue-validator(required, maxlength, etc.)?

You can the set the below.

``` js
Vue.validator('required', {
  message: function (field) { // string or function
     return 'required "' + field + '"' 
  },
  check: Vue.validator('required')
})
```

**Comment by felixpy** [comment]
Thx, I'll try it.
