### ISSUE TITLE
where can I find the build-in validators? I can't find it in document.

### ISSUE THREAD

**Issue by postgetme** [kazupon/vue-validator#247]
where can I find the build-in validators? I can't find them in document. Are there build-in 'email', 'ip', 'phone number' validators?

**Comment by guoweiTang** [comment]
The build-in validators contains required,pattern,minlength,maxlength,min,max

**Comment by postgetme** [comment]
@guoweiTang thanks for your reply, but where can I find the usage informatons of them?

**Comment by kazupon** [comment]
related #232

**Comment by kazupon** [comment]
I'll try to add the docs build-in validator.
