### ISSUE TITLE
dynamic validator support

### ISSUE THREAD

**Issue by sithuaung** [kazupon/vue-validator#249]
Hello @kazupon 
Sorry for mention. Could u check?

Does dynamic validator support now?
I have [jsfiddle](https://jsfiddle.net/sithuaung/uaqtzkyc/71/).
I can't get it to work yet.

Great work vue-validator. Thanks

**Comment by nandin-borjigin** [comment]
## Update

I've updated your jsfiddle and it works now, look at [here](https://jsfiddle.net/Nandiin/uaqtzkyc/77/)

The main idea is: keep using single validator scope but set the validator field name dynamically, [reference here](http://vuejs.github.io/vue-validator/en/syntax.html#attribute)

## Original

how about using [`Grouping`](http://vuejs.github.io/vue-validator/en/grouping.html)

**Comment by kazupon** [comment]
@webcrazy 
Thank you for your question.
The answer of is as above

@Nandiin 
Thanks!!

**Comment by sithuaung** [comment]
Thanks you so much @Nandiin and @kazupon.
