### ISSUE TITLE
Dirty on remote data? / Delay validation until data is loaded

### ISSUE THREAD

**Issue by JoshZA** [kazupon/vue-validator#25]
```
<template>
                <form accept-charset="utf-8" method="POST">
                    <div class="form-group required">
                        <label for="name" class="form-label">Name</label>

                        <div class="controls"><input id="name" class="form-control" type="text"
                                                     v-model="client.name" v-validate="required,minLength:3"></div>
                    </div>

                    <div class="form-actions"><input class="btn-primary btn" type="submit" value="Save Client" v-attr="disabled: invalid || !dirty"></div>
                </form>
</template>
<script>
    module.exports = {
        replace: true,
        props: ['params'],
        data: function () {
            return {
                params: {
                    clientEditId: null
                },
                client: null
            }
        },
        compiled: function () {
            this.update()
        },
        watch: {
            'params.clientEditId': 'update'
        },
        methods: {
            update: function () {
                var resource = this.$resource('/client/client/:id');
                resource.get({id: this.params.clientEditId}, function (item, status, request) {
                    this.client = item
                    this.dirty = false //doesn't work!
                }.bind(this))
            }
        },

    }
</script>
```

In this example, dirty() is always false, because the data->client has been changed from its initial state of null.

How can we disable validation until the data is loaded? 

Or set dirty = false, once the object has been loaded?

Thanks!

**Comment by kazupon** [comment]
Sorry for the late relpy.

We cannot disable validation in vue-validator.
if you want to use validation properties (dirty, valid and invalid) after you set the data with JS codes, you should use Vue.nextTick.

for more detail see:
http://vuejs.org/guide/best-practices.html#Understanding_Async_Updates

**Comment by JoshZA** [comment]
```
 update: function () {
                var resource = this.$resource('/client/client/:id');
                resource.get({id: this.params.clientEditId}, function (item, status, request) {
                    this.client = item
                    this.dirty = false
                    console.log('Dirty: ' + this.dirty)

                    this.$nextTick(function () {
                        console.log('Dirty: ' +this.dirty)
                    })
                }.bind(this))
            }
```

Thanks! Sadly, this isn't working for me, I'm still getting dirty == true, any way to reset it?

**Comment by kazupon** [comment]
Hmm, I understood your issue. :)

The vue-validator should probably support`wait-for` like of Vue.js component system.
http://vuejs.org/guide/components.html#wait-for

I'll try out whether become able to delay validation.

**Comment by kazupon** [comment]
I implemented delay initialization of validation.
https://github.com/vuejs/vue-validator#wait-for

You can try. :)

**Comment by JoshZA** [comment]
Arigato Kazupon

I would have preferred wait-for on the <form> element, and just a single $emit() call rather than 1 per field.

It might be worth mentioning in the docs, that $emit() only works for v-validate fields, and not the entire model (So non validated fields can't be set using this method).

Also I noticed 

``` HTML
<form id="user-profile">
    name: <input type="text" v-model="name" wait-for="name-loaded" v-validate=""><br />
    email: <input type="text" v-model="email" wait-for="email-loaded" v-validate=""><br />
    <input type="submit" value="send" v-if="valid && dirty">
</form>
```

If you make **v-validate** blank, the new code fails after the first item.

**Comment by kazupon** [comment]
Thanks for some your comments and bug.
I'll fix that bug.

Certainly, in vue-validator should change `$emit` only works for v-validate model fields, because current implementation can set the other model fields.

I think that a single `$emit` calling
will support the v2.0 later, because current implementation of vue-validator is bad design.

sorry poor my english :)

**Comment by swift1** [comment]
The wait-for parameter works, even when the element is not a component. In Vue.js, the wait-for parameter only works when the element is a component.

However, sometimes it's neccessary to reset the dirty flag during the lifespan of the application, for example when fetching new data asynchronously from the server. Currently, there's no easy way to reset the dirty flag after everything has been initialized.

**Comment by swift1** [comment]
I figured out a way to reset the dirty flags (which I need to do after having fetched new async data during the application lifespan, which can happen many times).

``` javascript
resetDirtyFlags: function(){
    for (var property in this.validation) {
        if (this.validation.hasOwnProperty(property)) {
            var keypath = property;
            this.$validator._setInitialValue(property, this.$data[keypath]);
            this.$validator._updateDirtyProperty(keypath, this.$validator.$get(keypath));
        }
    }
}
```

Though I don't know if this is best practice or not. A native function to reset the dirty flags would have been great.

**Comment by JoshZA** [comment]
@kazupon Is this working in 2.x ? I'm trying to use http://vuejs.org/guide/components.html#activate_Hook is this the correct way of doing it?

**Comment by JoshZA** [comment]
Think it's this one? https://github.com/vuejs/vue-validator/blob/dev/v2.0-spec.md#lazy-initialization-cahnge

**Comment by kazupon** [comment]
@JoshZA 
Sorry, i don't implement yet.
I'll implement.

**Comment by JoshZA** [comment]
:smiley_cat:

Might be worth looking at this too
http://vuejs.github.io/vue-router/en/pipeline/activate.html

**Comment by kazupon** [comment]
Thanks !!
I'll try to consider the your advise. :smiley_cat:
