### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by za-creature** [kazupon/vue-validator#26]
Pattern validation is broken for me in 1.1.0:

```
Uncaught TypeError: stripQuotes(...).match is not a function
 @ validates.js:39(anonymous function)
```

that seems to be caused by:

https://github.com/vuejs/vue-validator/commit/e51713269958afc1a680ad72066c8aa27c0b1f64#diff-91b538ee740fc9b485e0745f4fb39340R584

in combination with

https://github.com/vuejs/vue-validator/commit/e51713269958afc1a680ad72066c8aa27c0b1f64#diff-91b538ee740fc9b485e0745f4fb39340R490

**Comment by kazupon** [comment]
Thanks for your report. :)

**Comment by kazupon** [comment]
Fixed
