### ISSUE TITLE
Is there anyway to validate multiple form on one page?

### ISSUE THREAD

**Issue by zchking** [kazupon/vue-validator#264]
## Is there anyway to validate multiple form on one page?

Hi, when using  vue-validator with multiple form on one page, I call the **this.$validate()** through click the buttons, but it just validate the second form. The first form can not validate as expected. 

Is there anyway to validate with multiple form? thanks
### Reproduction Link

_http://codepen.io/zchking/pen/dXvvYz_

**Comment by kazupon** [comment]
related issue
https://github.com/vuejs/vue-validator/issues/220

Sorry, The `$validate` API doesn't support the multiple validation.
I'll try to support in v3

**Comment by zchking** [comment]
thanks :+1:
