### ISSUE TITLE
How to clear all validator's result?

### ISSUE THREAD

**Issue by ibufu** [kazupon/vue-validator#265]
For example, there is a dialog contains a form. And user inputs invalid data.So, there is some error message.Then user closes the dialog and opens it again. The data user input need to be clear and the old error message also need to be clear.

**Comment by kazupon** [comment]
You can use the `$setValidationErrors`.
See the detail: 
http://vuejs.github.io/vue-validator/en/api.html#setvalidationerrors-errors-

**Comment by kazupon** [comment]
Close (in-activity)
