### ISSUE TITLE
vue-validator for commonJS module is error

### ISSUE THREAD

**Issue by wklc2014** [kazupon/vue-validator#268]
### vue & vue-validator version

1.0.26, 2.1.3
### Steps to reproduce

```
<input type="text" v-validate:username="{required: true}">
                        <div class="errors">
                            <p v-if="$validator1.username.required">Required your name.</p>
                        </div>
                    </div>
```

console panel is allways show

```
vue.common.js:1935 Uncaught TypeError: Cannot read property 'required' of undefined
```
### What is actually happening?

This is use CommonJS module above, but when I use separate compilation of files that was right

**Comment by kazupon** [comment]
related https://github.com/vuejs/vue-validator/issues/130

**Comment by kazupon** [comment]
Close (in-activity)
