### ISSUE TITLE
unwatch is not a function

### ISSUE THREAD

**Issue by orestisioakeimidis** [kazupon/vue-validator#27]
Hi,

I am getting this error when using validator "unwatch is not a function". When I comment out the line "$validator._undefineModelValidationScope(key)" everything works again.

Cheers!

**Comment by kazupon** [comment]
Can you please provide example code in jsfiddle ?

**Comment by kazupon** [comment]
same #29 issues ?

**Comment by orestisioakeimidis** [comment]
Yes, seems to be the same! Great!
