### ISSUE TITLE
Сheck for empty string

### ISSUE THREAD

**Issue by serega270** [kazupon/vue-validator#271]
Hi guys, can't figure out how to check with vue-validator model to an empty string

```
<validator name="validation">
  <input type="text" v-model="name" v-validate:name="{ required: {rule: true}}">
  {{$validation.name | json}}
</validator>
```

If you enter only spaces, //valid": true

I can do it manual check using .trim(), but I would like to know how to do vue-validator

Is there any way to do this?

vue-validator: 2.1.3

**Comment by kazupon** [comment]
You can use the `pattern` validator.
see the below url
http://jsfiddle.net/kazupon/5um0mjta/1/

**Comment by serega270** [comment]
Sorry, but the `pattern` validates only the letter `'s'`, аnd do not miss anything else.
In your example, it is also seen http://jsfiddle.net/kazupon/5um0mjta/1/
Maybe there is a different pattern, but I can not find the right

**Comment by vip30** [comment]
http://jsfiddle.net/5um0mjta/2/

Now if the input is whitespace, it will be valid.
Is that what you need?

**Comment by serega270** [comment]
No. Sorry if I incorrectly asked the question.
I need to see if the user entered only whitespace and no other characters then valid = false

**Comment by vip30** [comment]
http://jsfiddle.net/5um0mjta/3/

`pattern: '/\\S/' }"`

Actually I think the main point is the pattern validator is working as expected.

**Comment by serega270** [comment]
Yes, this pattern works as I need. Thank you
