### ISSUE TITLE
Very strange exception

### ISSUE THREAD

**Issue by nandin-borjigin** [kazupon/vue-validator#276]
### vue & vue-validator version

1.0.25, 2.1.3
### Reproduction Link

The problem is heavily related to development environment, so I can't make a minimal reproduction sample.
### Steps to reproduce
- env: webpack-dev-server, vue-loader
- plugins: vue-router, vue-validatior
- problem:
  There is a component called 'Edit', it's mapped to a certain route via `vue-router`.
  Before introducing `vue-validator` all things worked fine. And then I put some validator code into it which causes the source code to throw an exception saying `Uncaught TypeError: Cannot read property 'required' of undefined`. I removed all validator code and added a small set of testing code like

``` html
<validator name="validation">
    <input v-validate:input="['required']">
</validator>
```

It still caused the exception.
And then, the VERY STRANGE thing happened: 
1. First, I commented this testing code out, and webpack-dev-server reloads the page and the page rendered correctly. 
2. Then I uncommented this testing code and webpack-dev-server made a HOT-UPDATE to apply the changes, it worked, the page got rendered correctly and validator worked fine ( I inspected the dom element and it's css class name changed according to my input). 
3. Finally, I made a manual full reload, i.e. pressing `Command + R`(`ctrl + R` for windows) to reload the page, that exception comes back.
The code was totally untouched between step 2 and 3, but the result was different.

I added a exception break point , and that exception comes from `resolveAsset` function, which is called from `BaseValidation.prototype._resolveValidator`.

The incoming arguments of `resolveAsset` function looks like:
- options: `Edit` components options
- type: string with value "validators"
- id: string with value "requried"

``` javascript
function resolveAsset(options, type, id, warnMissing) {
    // ... some code
    var assets = options[type] // assets = undefined here, because options don't have a property named validators, I think this is the point
    var res = assets[id] // throws exception because assets = undefined

}
```

It's very strange because hot-updating doesn't cause this exception but full reload does. I don't know if the details above are enough to figure out what's going wrong.

**Comment by nandin-borjigin** [comment]
I found a similar issue #188, the exception stack is extremly identical
I've tried to import and install validator before router, but it's still not working

**Comment by kazupon** [comment]
related #130

**Comment by nandin-borjigin** [comment]
Solved, watch my comment on [issue 130](https://github.com/vuejs/vue-validator/issues/130#issuecomment-232552739)
