### ISSUE TITLE
Several typos in 'Validation classes' doc page

### ISSUE THREAD

**Issue by gamtiq** [kazupon/vue-validator#278]
There are several typos in [Validation classes](https://github.com/vuejs/vue-validator/blob/dev/docs/en/classes.md) documentation page:

> if default _classs_ name
> In that case , we

The following typo occurs twice:

> output the _below below_ like the HTML

Also there is a typo in [API Reference](https://github.com/vuejs/vue-validator/blob/dev/docs/en/api.md) page:

> this._commont_ =  comment.body

**Comment by kazupon** [comment]
Thanks!!
