### ISSUE TITLE
Using this.$data creates an issue

### ISSUE THREAD

**Issue by lvismer** [kazupon/vue-validator#28]
Perhaps I am using the validator incorrectly. But for a specific case I am fetching some content using an ajax call inside a ready method and then wanting to set the content using `this.$data`. It would be cleaner if I can do that instead of setting every single property individually.

However as soon as I do that I get the following error from the console.

```
[Error] TypeError: undefined is not an object (evaluating 'last[key]')
    getTarget (bundle.js, line 1231)
    _doValidate (bundle.js, line 1207)
    (anonymous function) (bundle.js, line 9411)
    (anonymous function) (bundle.js, line 1138)
    wrappedCb (bundle.js, line 1362)
    run (bundle.js, line 10256)
    run (bundle.js, line 2109)
    flush (bundle.js, line 2095)
    handle (bundle.js, line 9246)
```

Here is a simplified [fiddle](http://jsfiddle.net/lvismer/25rag1zr/) to illustrate.

It works if I use `this.name = 'Caspien'` or `this.$set('name', 'Caspian')` inside the ready function.

**Comment by kazupon** [comment]
Thanks for your report.

I checked your jsfiddle.
But I could not understand that issue. 

Would you provide the issue code ?

**Comment by lvismer** [comment]
@kazupon Apologies, I pointed you to the original fiddle, I updated [version 2](http://jsfiddle.net/lvismer/25rag1zr/) to be the base.

It shows what I was trying todo. However, seems Evan updated to 0.12.4. I cannot even get a valid validation option to work with that.

**Comment by kazupon** [comment]
vue-validator don't work if you set  the new value to `this.$data`.
Because vue-validator keep the validation result to `this.$data`, and also define `valid`, `invalid` and `dirty` property. for that reason, we should  set the value `vm.$set('prop', val)` or `vm.prop = val`.

I think that is no good plugin design.
In next version 2.0, I'll try to  implement full-scratch (see #24).

**Comment by lvismer** [comment]
@kazupon thanks for response. In the end I did change my code to use vm.$set(...)
