### ISSUE TITLE
validator lower-cases camelCase v-models

### ISSUE THREAD

**Issue by jaredreich** [kazupon/vue-validator#282]
#### vue & vue-validator version: 1.0.21, 2.1.3

for example, within the template you are using:

``` html
v-model="dateFull"
v-validate:dateFull="{
  required: true
}"
```

then later in your methods, you try

``` javascript
this.$validator.dateFull
```

it will not work, but

``` javascript
this.$validator.datefull
```

will work... this can't be the desired behaviour?

**Comment by kazupon** [comment]
You can use the kebab-case in directive of HTML template. (This is HTML specification.)
See the detail:
http://vuejs.github.io/vue-validator/en/syntax.html#camelcase-property

**Comment by jaredreich** [comment]
thank you, sorry never saw this in the docs.
