### ISSUE TITLE
Using dot-notation syntax for v-validate field names

### ISSUE THREAD

**Issue by v-petukhov** [kazupon/vue-validator#286]
Hi there! 

Maybe it is bug or feature, i don't even know. 

But, here is description of a problem. 

If I use `initial="off"` directive and 'dot notation' syntax for `v-validate` field name, validation runs over last validation element only. But, if I'll change dots in `v-validate` field name for `'-'` -- all gonna be ok. 

Here is fiddle for example: [http://jsfiddle.net/d2tmqrzr/](url)

**Comment by kazupon** [comment]
vue-validator don't support field like object path. (e.g. `v-validate:user.name`)
you need to use simple field name or kebab-case (e.g. `user-name`)
