### ISSUE TITLE
detect-blur and detect-change have some bug.

### ISSUE THREAD

**Issue by vrbvillor** [kazupon/vue-validator#290]
The link : http://vuejs.github.io/vue-validator/en/timing.html
The example performs that when clicked the submit the filter `confirm` will check whether the `password` and the `confirm password` are equal when inputing in the `password`. But this performance will not occur if you haven't clicked the submit.

The defination of `detect-blur` and `detect-change` are not to check the validation of the components when inputing, aren't they?  But now they are checked when inputing after clicked the submit.

All the other checkings work as thought, only the customizing one `confirm` goes wrong.

**Comment by kazupon** [comment]
This is not bug.
This is the `submit` specification.

Please see the below URL.
http://www.w3.org/TR/html5/forms.html#implicit-submission

**Comment by vrbvillor** [comment]
Is the detect-blur="off" and detect-change="off" the switch to turn off the validation before submit? But it validate when inputing. It works as thought before clicking the submit. Means before clicking the submit, the password doesn't check the equality between password and confirmpassword.
