### ISSUE TITLE
resetValidation() and initial: 'off' not working on select element

### ISSUE THREAD

**Issue by tehciolo** [kazupon/vue-validator#299]
### vue & vue-validator version

1.0.26, 2.1.16
### Reproduction Link

http://jsfiddle.net/tehciolo/5sH6A/617/
### Steps to reproduce
- Choose an option from a select that has a required validator attached (with `initial: 'off'`).
- Call `resetValidation()`.
### What is Expected?

Validator does not throw error on select field.
### What is actually happening?

Validator throws error on select field.

---

The `initial: 'off'` works fine on inputs, as can be seen from the fiddle. It just fails to do so on selects.

I have applied a [hacky solution](http://jsfiddle.net/tehciolo/vmo3xwv7/1/), but would like to know if I am missing something.

**Comment by kazupon** [comment]
related #307

**Comment by kazupon** [comment]
fixed v2.1.7
https://github.com/vuejs/vue-validator/releases/tag/v2.1.7
