### ISSUE TITLE
Travis setting

### ISSUE THREAD

**Issue by kazupon** [kazupon/vue-validator#3]
@vuejs/owners 
I could not run the travis-ci.
I want to run the travis-ci.
Would you set the travis-ci ?

The following is a screen when an error occurs at the travis-ci.
![screen shot 2015-01-31 at 1 39 17 am](https://cloud.githubusercontent.com/assets/72989/5979532/dd531c92-a8eb-11e4-8a8e-c0f8ff2ca355.png)

**Comment by yyx990803** [comment]
I've added you to the owners group, let me know if this helps.

**Comment by kazupon** [comment]
@yyx990803 
thanks !!
