### ISSUE TITLE
Missing image on "Getting started"

### ISSUE THREAD

**Issue by kluplau** [kazupon/vue-validator#301]
### vue & vue-validator version

1.0.26
### Reproduction Link

http://vuejs.github.io/vue-validator/en/started.html
### Steps to reproduce

Go to the documentation link in a browser.
### What is Expected?

An image at the very bottom with alt=":warning"
### What is actually happening?

404 on [image](http://vuejs.github.io/vue-validator/en/gitbook/gitbook-plugin-advanced-emoji/emojis/warning.png)

**Comment by kazupon** [comment]
Fixed
