### ISSUE TITLE
resetValidation appears to not work

### ISSUE THREAD

**Issue by cpinto** [kazupon/vue-validator#307]
### vue & vue-validator version

2.1.6
### Reproduction Link

http://jsfiddle.net/fLpmjn52/
### Steps to reproduce
1. click the show button
2. type in anything in the username field
3. click the hide button
4. click the show button again
### What is Expected?

After clicking the show button for a second time, as the component data is reset I was expecting the validation errors to be dismissed.

**Comment by cpinto** [comment]
updated the ticket with a better reproduction

**Comment by kazupon** [comment]
Sorry for the late response.
I checked your reproduction code.
I'll try to improve this issue at `2.2`

**Comment by kazupon** [comment]
fixed v2.1.7
https://github.com/vuejs/vue-validator/releases/tag/v2.1.7
