### ISSUE TITLE
Validation on child items

### ISSUE THREAD

**Issue by lvismer** [kazupon/vue-validator#31]
Trying to get validation to work when using a `v-repeat` directive, as per [fiddle](http://jsfiddle.net/lvismer/0s6a374x/). (Sorry I had to paste the contents of vue-validator as part of the js otherwise it did not work using github as a raw resource).

Is it possible to use the validator like this?

**Comment by kazupon** [comment]
Sorry for the late relpy.

Not support the array-able model.
I'm going to support at next version (v2.0). :)

**Comment by lvismer** [comment]
@kazupon Thanks for the reply, that is great. Is there a roadmap regarding version 2. Just a guess from your part. Weeks, months or years away.

**Comment by kazupon** [comment]
@lvismer 
As soon as possible, I think that want to release v2.0 version. :)

But I cannot be too secure my private time recently.
The reason need to keep the my family time and busy with work.

Please wait a little more. :pray:

**Comment by lvismer** [comment]
@kazupon Thanks for all the efforts

**Comment by shuogawa** [comment]
@kazupon 
Thank you for great library!
素晴らしいライブラリをありがとうございます!

I am waiting that vue-validator will support v-repeat too.

**Comment by kazupon** [comment]
@shuogawa 
Thanks !!

**Comment by Shiak1** [comment]
Thanks much!!!

**Comment by kazupon** [comment]
I published 2.0.0-alpha.1
