### ISSUE TITLE
How to use without module loading ?

### ISSUE THREAD

**Issue by valeriob** [kazupon/vue-validator#313]
Something like Vue.use(VueValidator); ?

thanks

**Comment by sqal** [comment]
It installs itself automatically, you don't need to do `Vue.use(validator)` https://github.com/vuejs/vue-validator/blob/dev/src/index.js#L18

**Comment by kazupon** [comment]
sorry, our poor documentation. 
http://vuejs.github.io/vue-validator/en/installation.html
vue-validator is providing same as the [vue.js installation](http://vuejs.org/guide/installation.html).

**Comment by valeriob** [comment]
Oh thanks, then i must be doing something wrong : 
using vuejs v1.0.22 and vue.validator 1.4.4 i get this error message with this html

<input class="form-control" v-model="model.MyProperty" v-validate="required">

vue.js:1018 [Vue warn]: Failed to resolve directive: validatewarn @ vue.js:1018resolveAsset @ vue.js:1936compileDirectives @ vue.js:7483compileElement @ vue.js:7095compileNode @ vue.js:7051compileNodeList @ vue.js:7234compileNodeList @ vue.js:7235compileNodeList @ vue.js:7235compileNodeList @ vue.js:7235compile @ vue.js:6837FragmentFactory @ vue.js:3931bind @ vue.js:4010Directive._bind @ vue.js:8277linkAndCapture @ vue.js:6880compositeLinkFn @ vue.js:6856Vue._compile @ vue.js:8563Vue.$mount @ vue.js:9398Vue._init @ vue.js:2460Vue @ vue.js:9462(anonymous function) @ 257:361

Is there some rule to use some validator version with vue version ?
Thanks,
