### ISSUE TITLE
version 1.2.1 breaks with error: Cannot read property 'validates' of undefined

### ISSUE THREAD

**Issue by cheapsteak** [kazupon/vue-validator#32]
http://jsfiddle.net/rkbLmpo7/1/

Using the dist files from both the vue and vue-validator repos, this currently results in an error.

`vm.$options.validator` is undefined. It seems like the plugin isn't being installed correctly

edit: this seems to be specific to the lastest version - 1.2.1. works fine in 1.2.0

**Comment by kazupon** [comment]
Thanks for your bug report.
Sorry my mistake. :bow: 

I fixed now.
You can try it !!

**Comment by cheapsteak** [comment]
It works! 
Thank you for the quick fix :smiley:
