### ISSUE TITLE
Can I use vue-validator and this custom input component? 

### ISSUE THREAD

**Issue by lavezzi1** [kazupon/vue-validator#322]
### vue & vue-validator version

1.0.28, 2.1.7

Hello! Can I use vue-validator and this custom input component? https://josephuspaye.github.io/Keen-UI/#/ui-textbox-docs

**Comment by kazupon** [comment]
ref #257 

Yes, You can use the validation on custom component.

**Comment by lavezzi1** [comment]
Thanks. Where I can see some examples? I curios how to pass the directive like `v-validate:name`
