### ISSUE TITLE
when support vue2.0

### ISSUE THREAD

**Issue by joe434200** [kazupon/vue-validator#325]
I just waiting fot a lot... could you tell me about the date for support vue2.0 ?? hope to know thks

**Comment by miedzinski** [comment]
Soon. #257

**Comment by joe434200** [comment]
A week?

**Comment by nblackburn** [comment]
The first alpha is available now: https://github.com/vuejs/vue-validator/issues/257#issuecomment-255720218, fancy closing this?

**Comment by joe434200** [comment]
ok, so happy !! hooo
