### ISSUE TITLE
vue-validator单词错误（在gitbook文档上）

### ISSUE THREAD

**Issue by gongph** [kazupon/vue-validator#326]
[延迟初始化](http://vuejs.github.io/vue-validator/zh-cn/lazy.html#)这一章节的实例代码中的 Vue生命周期钩子 `activate` 是不是写错了？ 是不是少个 `d`  ？ 正确的写法是： `activated`

**Comment by kazupon** [comment]
sorry, can you speak english please?

**Comment by kazupon** [comment]
Close (in-activity)
