### ISSUE TITLE
unregister looks for non-existent field

### ISSUE THREAD

**Issue by heygambo** [kazupon/vue-validator#336]
### vue & vue-validator version

2.0.3, 3.0.0-alpha.1
## Problem

There is a callback being called when I destroy a the Vue component.
That leads the validator's unregister function to be called.

It always leads to an error that I cannot make any sense of so far.

It iterates two times. The first time is correct, but `this._validityWatchers` changes in the second run so that the watcher cannot be found.

![screenshot 2016-10-29 19 34 34](https://cloud.githubusercontent.com/assets/449438/19831626/1ace773c-9e0f-11e6-9d62-253b3ad6f76d.png)
## Code

That's the template:

``` vue
<template>
  <validation name="validation">
    <form novalidate @submit.prevent="submit">
      <validity field="complaint" group="dispute" :validators="{ required: true, minlength: 4 }">
        <input @input="handleValidate" id="complaint" type="text">
      </validity>
      <validity field="body" group="dispute" :validators="{ required: true, minlength: 4 }">
        <textarea @input="handleValidate" id="body"></textarea>
      </validity>
    </form>
  </validation>
</template>
```
## Screenshots

![vue-validator-unregister-1](https://cloud.githubusercontent.com/assets/449438/19831601/5c09c702-9e0e-11e6-865a-72b7fd7c5461.png)

![vue-validator-unregister-2](https://cloud.githubusercontent.com/assets/449438/19831602/5c24a4c8-9e0e-11e6-8f89-1c8045bd4440.png)

**Comment by kazupon** [comment]
Thank you for your feedback!
I'll try to fix next release.

**Comment by woshi82** [comment]
I have meet this problem too , ……
