### ISSUE TITLE
使用validator情况下调用$destroy() 抛错

### ISSUE THREAD

**Issue by jackzhaojun** [kazupon/vue-validator#338]
### vue & vue-validator version
2.0.3, 3.0.0-alpha.1

按照你的示例[https://github.com/vuejs/vue-validator/blob/dev/examples/started/index.html]( https://github.com/vuejs/vue-validator/blob/dev/examples/started/index.html)

vue实例化后，调用vm.$destroy()方法后会抛出以下错误。

Uncaught TypeError: this._validityWatchers[name] is not a function(…)

![image](https://cloud.githubusercontent.com/assets/3805455/20059566/d4634ea6-a531-11e6-9595-d74f72177553.png)

**Comment by kazupon** [comment]
Thanks for your feedback.
I'll try to fix until official release, at the latest.

**Comment by yuanzm** [comment]
@kazupon +1

**Comment by chengchengcs** [comment]
我也遇到了，怎么破 @kazupon

**Comment by chuangker** [comment]
+1, 有没有临时解决方案。切换路由就报错

**Comment by DearVikki** [comment]
+1, 我也是刚在切换路由的时候就报一样的错了!!但是若刷新一遍就完好无误。
