### ISSUE TITLE
v-validate does not work with v-class

### ISSUE THREAD

**Issue by levelel** [kazupon/vue-validator#34]
My html code

``` html
<div class="current_page item">
    <div class="ui input" v-class="error: validation.current_page.invalid">
        <input type="text" v-model="current_page" number v-validate="min: 1, max: 9" v-on="keyup: onGoToPage | key 'enter'">
    </div>
</div>
```

Whatever numbers typed in the field, the v-class won't work.

**Comment by kazupon** [comment]
I tried the your issues on the jsfiddle.

https://jsfiddle.net/kazupon/q7xcbuxd/6/

It seems to work normally.

Can you give me your issue code on the jsfiddle ?

**Comment by danielchou** [comment]
@kazupon 
Hi, in your sample, VueJS file been blocked since it request by http resouce, jsfiddle now has supported https.

**Comment by kazupon** [comment]
I updated sample.

https://jsfiddle.net/kazupon/q7xcbuxd/8/

**Comment by danielchou** [comment]
@kazupon  It's a great sample for vue-validator. :+1:  
I fork one for adding an error effect to make it clear. https://jsfiddle.net/vz5rLzny/

**Comment by levelel** [comment]
I see, I didn't get this line in my code.

``` javascript
Vue.use(window['vue-validator'])
```
