### ISSUE TITLE
vue.common.js?e881:511 [Vue warn]: Unknown custom element: <validator> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 

### ISSUE THREAD

**Issue by yonycat** [kazupon/vue-validator#345]
Version of vuejs: 2.1.0
Version of vue-validator: ^3.0.0-alpha.1

I  vue init vue-validator in this way:
`
import Vue from 'vue'
Vue.use(VueValidator)
`
then in my login web component:
i use it in this way:
`html
<validator name="login">
        <div class="m-login">
          <div class="form-group">
            <label for="username">username</label>
            <input type="text" class="form-control" id="username">
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control">
          </div>
          <div class="from-group">
            <button type="submit" class="btn btn-default">Submit</button>
          </div>
        </div>
      </validator>
`
But I  got vuejs warn  that validator  custom element is not registered.

vue.common.js?e881:511 [Vue warn]: Unknown custom element: <validator> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by huhk-sysu** [comment]
I came across the same error. It seems that the example is for vue-validator v2. And in v3 the directive "validator" was abandoned and they use "validation" instead.

Check this [example](https://github.com/kazupon/vue-validator/blob/dev/examples/validation/index.html).

**Comment by yonycat** [comment]
@huhk-sysu Thank you very much.It works.
