### ISSUE TITLE
[3.0.0-alpha.2] validate method callback is called twice or more(?)

### ISSUE THREAD

**Issue by sqal** [kazupon/vue-validator#352]
### vue & vue-validator version
vue@2.1.8, vue-validator@3.0.0-alpha.2

### Reproduction Link
https://jsfiddle.net/sqal/21jse27u/

### Steps to reproduce
1. Open reproduction link
2. Type something in input field
3. In console you should see that it logs `validate callback` twice every time you enter a value into input field

I am guessing it's called twice because I use two validators in my example?. But still is this correct behaviour? I can't remember this callback being called multiple times in vue-validator 2.x, So just want to make sure whether or not this is a bug or by design. Thanks :)

**Comment by kazupon** [comment]
Thank you for your feedback.

yes, `validate` method have some issues.
I'll improvement `validate` method.
