### ISSUE TITLE
Bug with the dirty-function?

### ISSUE THREAD

**Issue by swift1** [kazupon/vue-validator#36]
Hi guys! I've tried everything and I still can't get the dirty function to work properly, except when the data value is a number.

I initialize the form and set a string value, but as soon as the form loads, the validator thinks it's dirty. And when the text is removed, it thinks it's not dirty (even though it is).

Am I doing something wrong here?

https://jsfiddle.net/q7xcbuxd/10/

**Comment by swift1** [comment]
I solved the first part: the 'name' property cannot be used, since it is a reserved word. When changing the property from 'name' to 'namee', the dirty checking works on that property. However, the dirty checking for the whole form is still bugged:

https://jsfiddle.net/q7xcbuxd/11/

The form is only considered to be dirty when **all** of its properties are dirty (and it should consider the form dirty if **one or more** of its properties are dirty).

***_EDIT: I patched it!**_*
With this function, the dirty function works as expected (dirty form = one or more properties are dirty):

``` javascript
computed: { 
    formIsDirty: function() {
        for (var property in this.validation) {
            if (this.validation.hasOwnProperty(property)) {
                if (this.validation[property].dirty)
                    return true;
            }
        }
        return false;
    }
}
```

https://jsfiddle.net/q7xcbuxd/12/

**Comment by kazupon** [comment]
Thanks for your issue.

I think that the behavior of dirty is bug.
I'll try fix.

**Comment by kazupon** [comment]
I fixed.
Please try !!

**Comment by swift1** [comment]
Thanks, it works fine now. :+1:
