### ISSUE TITLE
Question about the dirty property

### ISSUE THREAD

**Issue by swift1** [kazupon/vue-validator#39]
Hi!

I'm not sure if this is a bug or if it's supposed to be like this, but the dirty property will only work if the element has a `v-validate` property.

Sometimes, it would be nice to see if a property (or a form) is dirty without putting an actual validator on every single element in the form. `v-validate=""` doesn't work, so I guess the only way to do this at the moment is to write a custom validator that always returns true, or to use something like `v-validate="minLength: 0"`

Example:
https://jsfiddle.net/q7xcbuxd/31/

**Comment by kazupon** [comment]
Sorry for the late relpy.

Hmm ..., Currently , `v-validate` directive is required of something validator.
if you want to only use dirty property in `vue-validator`, you said as follow ways:
- write a custom validator that always returns true
- use something like `v-validate="minLength: 0"`

I think you can satisfy your desire for the time being.

in v2.0 of `vue-valdiator`, I think that want to consider this feature. :smile_cat:

**Comment by swift1** [comment]
Thanks for the reply! :smile: :smile_cat:
