### ISSUE TITLE
Custom validator params

### ISSUE THREAD

**Issue by fourstacks** [kazupon/vue-validator#40]
Hi

Does anyone know if there's a way to pass anything other than a string to a custom validator?  My use case is as follows:

I have a form field that is only displayed (via v-show) if another field (radio button) is set to a certain value by the user.  I have this working fine.  What I'd now like to do is only require this field if is being displayed so basically I need a custom validator along the lines of requiredIf .

In proto code my app.js looks like this:

```
data: {
    response: '",
    approveMessage: "",
    declineMessage: ""
},
validator: {
    validates: {
        requiredIf: function(val, condition){
            console.log(condition);
            // My required logic goes here
        }
    }
}
```

On my form fields I have the following:

```
<label for="response">How do you want to respond?</label>
<input id="response_approve" v-model="response" checked="checked" name="response" type="radio" value="approve">
<label for="response_approve" >approve</label>

<input id="response_decline" v-model="response" name="response" type="radio" value="decline">
<label for="response_decline" >decline</label>


<div v-show="conditionalField('response', 'approve')" v-class="has-fe-error: validation.approved_message.invalid">
    <label for="approved_message">Approved message</label>
    <textarea v-model="approved_message" v-validate="requiredIf: conditionalField('response', 'decline'), maxLength: 500" name="approved_message" cols="50" rows="10" id="approved_message"></textarea>
</div>

<div v-show="conditionalField('response', 'decline')" v-class="has-fe-error: validation.declined_message.invalid">
    <label for="declined_message">Declined message</label>
    <textarea v-model="declined_message"  v-validate="requiredIf: conditionalField('response', 'decline'), maxLength: 500" name="declined_message" cols="50" rows="10" id="declined_message"></textarea>
</div>
```

In this example the method called conditionalField just get's pass through as a string (the method itself shows/hides fields just fine so I know it works) and if instead I use an inline expression such as:

```
v-validate="requiredIf: response == 'decline'
```

this also get's passed through as a string.  Is there any way to pass through either a method, an inline expression or even just more than one expression after the requiredIf argument?

**Comment by kazupon** [comment]
@FourStacks 

Thank you for your feedback !!

I understood your usecase. :smiley: 
Currently, `vue-validator` does not support function or inline expression like `v-on`.

http://vuejs.org/guide/events.html
http://vuejs.org/api/directives.html#v-on

It's very convenient !!
I will try to support.

**Comment by fourstacks** [comment]
Hi @kazupon 

Thanks for the quick reply!  Yeah - if that's something that could be included it would be very handy indeed and would allow for more complex custom validators.  Thanks for offering to look into it!

**Comment by kazupon** [comment]
I published v1.4.0 release.

Example:
https://jsfiddle.net/kazupon/76q3Lxu2/7/

Please try it !!

**Comment by fourstacks** [comment]
Excellent!  Thanks very much for the speedy work in getting this implemented - very much appreciated!

**Comment by fourstacks** [comment]
Seems to work like a charm by the way, judging from the fiddle.  I'll integrate it into my code later today and let you know if I spot any issues but it's looking great!

**Comment by gitteri** [comment]
I can't get something like this working with v2.0 alpha. Any ideas?
