### ISSUE TITLE
2.0 plan

### ISSUE THREAD

**Issue by kazupon** [kazupon/vue-validator#41]
Hi everyone !!

I'm planning for the v2.0 release.
I will start development on `dev/latest` branch at an early date.

I have been publish the v1.0 release, fixed some bugs and adopted some user feedbacks.

I think that want to adopt the user coming feedback to v1.0 implementation, but v1.0 implementation is bad design.
Even if i adopting the user coming feedback, the bug occur easily.

For these reasons, I have decided to implement the v2.0 with full-scratch.

I did rework the specification once again.
The following specifications (sorry my poor english):
## spec
- custom element (e.g. `<v-validator></v-validator>`)
  - custom element enable validation result scope that did **inherit** from user data scope. vue-validator do not operate user data via validation result scope
  - `id` attribute: keep the validation result data in custom element (e.g. vm.$validators.validator1)
  - `name` attribute: change the validator result scope namespace (e.g. default: `validity`)
  - available multiple validator (e.g. vm.$validators.validator1, vm.$validators.validator2, ...)
- set custom directive (`v-validate`) to target element
  - specify **field name**: keep the validation result
  - validation result format: object property base structure (e.g. `validity.field.constraint`)
  - accessable validation result with property keypath base (e.g. `validity.username.xxx`)
- support for each field, the following validation property
  - `valid` (e.g. `validity.field.valid`)
  - `invalid` (reverse of `valid`, e.g. `validity.field.invalid`)
  - `modified` (from **initial** field value, e.g. `validity.field.modified`)
  - `dirty` (angluar-like, attached even **once**, e.g. `validity.field.dirty`)
  - `pristine` (angluar-like, **not** attached even once, e.g. `validity.field.pristine`)
- support the following top level property that keep the validation result of all fields
  - `valid` (when **all** property is valid, return `true`)
  - `invalid` (if exist even **one** invalid property, return `true`)
  - `modified` (if exist even **one** modified property, return `true`)
  - `dirty` (if exist even **one** dirty property, return `true`)
  - `pristine` (if exist even **one** pristine property, return `true`)
- build-in validators
  - required
  - pattern
  - min
  - max
  - minLength
  - maxLength
- improve delay validator initialization feature
  - custom element base (not for each custom directive)
- validator use HTML5 Form attributes base. (e.g. `min`, `max` ...)
  - support custom validator: use attribute (e.g. `myValidator1` -> `<input type="text" my-validator1="foo">`)
  - support reactivity & function or inline expression like `v-on`: `{{ mustache }}` expressions (e.g. `<input type="text" min="{{constraints.min}}">`)
  - support async validator
- validator assets feature
  - aseets management: like vue.js
  - register/retrieve custom validator or build-in validtors
## sample code

``` html
<div id="app">
    <h1>user registration</h1>
    <v-validator id="validator1">
        <form>
            username:<input type="text" required maxLength="16" pattern="/[a-zA-Z0-9_-]/" exist v-validate="username"><br>
            age:<input type="number" required min="{{constraints.age.min}}" max="{{constraintAgeMax}}" v-validate="age"><br>
            email:<input type="email" required email v-validate="email"><br>
            password:<input type="password" required minLength="8" v-validate="password"><br>
            site:<input type="number" url v-validate="site"><br>
            <button type="submit" value="join" v-class="disabled: invalid"><br>
            <div>
                <span v-if="validity.username.required">required username.</span>
                <span v-if="validity.username.maxLength">too long username.</span>
                <span v-if="validity.username.pattern">invalid username format.</span>
                <span v-if="validity.username.exsit">already exist username.</span>
                <span v-if="validity.age.required">required age.</span>
                <span v-if="validity.age.min">too small age.</span>
                <span v-if="validity.age.max">too big age.</span>
                <span v-if="validity.email.required">required email.</span>
                <span v-if="validity.email.email">invalid email format.</span>
                <span v-if="validity.password.required">required password.</span>
                <span v-if="validity.password.minLength">too short password.</span>
                <span v-if="validity.site.url">invalid site url format.</span>
            </div>
        </form>
    <v-validator>
</div>
```

``` javascript
var Vue = require('vue')
var VueValidator = require('vue-validator')

//
// register custom validators with validator assets
//

// url validator, sync validation
VueValidator.asset('url', function (val) {
    return /^(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?$/.test(val)
})

// exist validator, async validaiton
Vuevalidator.asset('exist', function (val) {
    return function (resolve, reject) {
        // server-side validation with ajax (e.g. using `fetch` case)
        fetch('/validators/exist', {
            method: 'post',
            headers: {
                'content-type': 'application/json',
                'x-token': 'xxxxxxxx'
            },
            body: JSON.stringify({ username: val })
        }).then(function (res) {
            if (res.status === 200) {
                resolve(true)
            } else if (res.status === 400) {
                resolve(false)
            }
        }).catch(function (err) {
            // something todo ...
            reject(new Error('exist validator fail'))
        })
    }
})

// email validator, async validation
VueValidator.asset('email', function (val) {
    return function (resolve, reject) {
        // something todo ...
    }
})

// install vue-validator
Vue.use(VueValidator)

// create Vue instance
new Vue({
    data: {
        constraints: {
            age: {
                min: 18,
            }
        },
        name: '',
        age: 18,
        email: '',
        password: ''
    },
    computed: {
        constraintAgeMax: function () {
            return this.constraints.age.min * 5
        }
    }
}).$mount('#app')
```

**NOTE:**
This is just a tentative specification.

**Comment by yyx990803** [comment]
Should `minLength` and `maxLength` be `min-length` and `max-length` instead? Since HTML attributes are case-insensitive.

I think we are moving towards a convention where everything is dash-cased as HTML attributes and camelCased in JavaScript / expressions.

**Comment by yyx990803** [comment]
BTW I like the new syntax using attributes :+1:

**Comment by swift1** [comment]
@kazupon M8, you've fixed all the bugs I've reported, so I don't really care if you release 2.0 or not; I'm happy with the current version. :blush: That being said, I do support your efforts and I will definitely continue to use your library, even though there are other Vue.js validation libraries out there.
However, if I were to pick and choose what I'd like to see implemented in 2.0, it would be:

1) a function to reset the dirty property (which can be relevant when the program is receiving async data multiple times), as discussed in:
https://github.com/vuejs/vue-validator/issues/25

My proposed solution is:

``` javascript
resetDirtyFlags: function(){
    for (var property in this.validation) {
        if (this.validation.hasOwnProperty(property)) {
            var keypath = property;
            this.$validator._setInitialValue(property, this.$data[keypath]);
            this.$validator._updateDirtyProperty(keypath, this.$validator.$get(keypath));
        }
    }
}
```

(This function works for the current version of the validator, but will probably be totally different in 2.0, if you decide to implement it.)

2) a way to track the dirty property of a form without having to designate a validator to every property

And by the way, there's no need to excuse your English, mate. I think you're doing a great job for the Vue.js community! :+1: Keep up the good work!

**Comment by kazupon** [comment]
@yyx990803 

> I think we are moving towards a convention where everything is dash-cased as HTML attributes and camelCased in JavaScript / expressions.

Yeah !! That's right.
We should move towards the Vue convention to keep the consistency.

But i think that some attributes which defined as a HTML5 Form specification should conform to the those standards.
Because it is easy to understand for users.

HTML5 Form specification - W3C
http://www.w3.org/TR/html5/forms.html#the-maxlength-and-minlength-attributes

However, I think that user defined HTML attributes (custom validators) is dash-cased as attributes and camelCased in JavaScript / expressions.

**Comment by kazupon** [comment]
@swift1 
Thank you for using and your feedback until now.
I'll try to adopt your request. :smile_cat:

**Comment by fergaldoyle** [comment]
How about support for "custom form elements"? 

e.g. If I write a component or directive to work with TinyMCE inline editor (which uses a div with contenteditable=true), I'd like to be able to utilize the same kind of validation as a normal textarea. From within my component / directive, if I could somehow hook into `v-validate` and set the `valid`, `invalid`, `dirty` etc properties so I can display validation messages for those states. Is this something already possible or something you'd consider for 2.0?

**Comment by Pandahisham** [comment]
@kazupon Wonderfull work , like the syntax

**Comment by Pandahisham** [comment]
btw vue has a lot of follower in the laravel community , built in validations that match laravel 's would be charming , but that can be debounced for later i guess

**Comment by kazupon** [comment]
@fergaldoyle 
Thank you for your feedback.
I'll try to consider about hook of `v-validate`. :smiley:

**Comment by nkovacs** [comment]
Shouldn't the top-level pristine be true only if all the attributes are pristine?

**Comment by kazupon** [comment]
@nkovacs 
Thank you for your comment.

Yes, you are right !! :)

**Comment by swift1** [comment]
If one or more properties are dirty, the form is dirty.
If none of the properties are dirty, the form is pristine.
So what's the point in having a pristine attribute? Pristine is just the same as `!dirty` (the opposite of dirty), right? :smile_cat:

**Comment by kazupon** [comment]
@swift1 
Yes,  That's right !! :smile_cat: 
I feel bad that my English made you confused.

**Comment by franciscolourenco** [comment]
Can we support automatic class names for each validation property like in https://github.com/xrado/vue-validator/ ?

That would spare the use of  v-class="error: ..." and make the code more concise while allowing all the styling to be done in css.

To avoid collision with existing classes a prefix could be used like:
- v-valid
- v-invalid
- v-modified
- v-dirty
- v-pristine

**Comment by franciscolourenco** [comment]
More built-in validators would be nice as well, for example: `numeric`, `email`

**Comment by kazupon** [comment]
@aristidesfl 
Thank you for your feedbacks !!
Looks pretty good about class attribute insertion.

I'll try to consider your feedback including as new feature.

**Comment by franciscolourenco** [comment]
A blur attribute would be useful as well. 
How can you achieve lazy validation during the first attempt, and after the element has been blurred, start validating on every keystroke?

**Comment by trippo80** [comment]
@aristidesfl For validating on blur you can use the directive lazy which would perform model update on change event instead of keystroke. However - this would affect all validation on that element so you can't (for example) do keystroke validation on length and then custom validation on blur/change.

**Comment by franciscolourenco** [comment]
@trippo80 That is the point, we want to disable the lazy directive after the first blur, so that the validation is on keystroke after the first blur.

**Comment by trippo80** [comment]
@aristidesfl Yeah I understod that. I thought you were asking two separate things. First how you could validate on blur, and then how you could do that a bit more advanced. Sorry for not reading well enough :)

**Comment by kazupon** [comment]
@aristidesfl @trippo80 
In currently version, vue-validator don't support lazy validation with the various events triggering,  like `blur`, `keyup`, `submit`, etc.

I'll try to consider your  feedback including as improvement point.

**Comment by trippo80** [comment]
@kazupon Hm maybe I don't understand you correctly - but I'm using lazy validation now with vue-validator and it works fine. I achieved this by using the lazy directive which seems to work fine. 

However - it won't fully facilitate the request from @aristidesfl .

**Comment by shinygang** [comment]
好久发布2.0啊？现在我用1.4.4的时候有bug.当我v-model="book.username" v-validate="required"的时候，我validation.book.username.required就不起作用，

**Comment by kazupon** [comment]
@shinygang 
Sorry, I don't understand chinese.
Could you tell me with english ?

**Comment by shinygang** [comment]
@kazupon
How long will the v2.0 release? There's a bug in v1.4.4, I think.   "validation.book.username.required" was not working when I use 'v-model="book.username" v-validate="required" '

**Comment by kazupon** [comment]
@shinygang 
Thank you for your comment with english :smile_cat: 

> How long will the v2.0 release?

As written [here](https://github.com/vuejs/vue-validator/issues/67),  I'm hard to work because I'm translating for japanese users now.
I may not be guaranteed to your desired schedule.

> There's a bug in v1.4.4, I think. "validation.book.username.required" was not working when I use 'v-model="book.username" v-validate="required" '

Sorry, I didn't understood.
I hope you will provide issue code with jsfiddle or codepen, and please open the new issue. :smiley_cat:

**Comment by swift1** [comment]
@kazupon gg! :smiley_cat:

**Comment by kazupon** [comment]
Release v2.0.0
https://github.com/vuejs/vue-validator/releases/tag/v2.0.0
