### ISSUE TITLE
How can I do validation depending on another field?

### ISSUE THREAD

**Issue by endaaman** [kazupon/vue-validator#42]
Using following codes,

``` js
vm = new Vue({
  data: {
    password: '',
    reenteredPassword: ''
  },
  validator: {
    validates: {
      matchPassword: function(v) {
        return v === this.password;
      }
    }
  },
  // SNIP..
```

``` html
<div>
    <div>
        <label>Password</label>
        <input type="password" v-model="password" />
    </div>
</div>
<div>
    <div>
        <label >Confirm password</label>
        <input type="password" v-model="reenteredPassword" v-validate="required, matchPassword" />
    </div>
    <div v-show="validation.reenteredPassword.dirty">
        <div v-show="validation.reenteredPassword.matchPassword">doesn't match password</div>
    </div>
</div>
```

if you change `reenteredPassword` and it doesn't match `password`, validation will be updated and `doesn't match password` will be displayed. But if you change `password` and it doesn't match  `reenteredPassword`, validation will **not** be updated.

How can I do validation depending on another field? Or, how can I perform validation explicitly on watcher like `vm.$watch('password', function..` ?

**Comment by kazupon** [comment]
One of solutions, I think that you  can resolve by specifying  computed property to custom validator.

example:
https://jsfiddle.net/kazupon/kdvdvdze/7/

**Comment by endaaman** [comment]
Oh, I didn't realize to use `computed` at all. This resolves my problem. Thank you very much.

**Comment by zschuessler** [comment]
For anyone else finding this in Google, there is a stock validator "confirmed" you can use. The docs are a little sparse on how it behaves, so I wrote up a CodePen demo you can find here:

http://zaclee.net/vue/password-confirmation-validation-with-vue-and-vee-validate

This way your code will stay clean!
