### ISSUE TITLE
Bug in the validator?

### ISSUE THREAD

**Issue by swift1** [kazupon/vue-validator#43]
Consider the following example:
https://jsfiddle.net/q7xcbuxd/37/

Then remove the apostrophes from the `mode` variable to make it an integer and run the example again. Click on "second", then "first".

```
data: {
    mode: 0
}
```

Result:
The form gets initialized to dirty, then when clicking on the radio buttons a couple of times it starts to work as expected again. The reason is probably because it gets initialized as an integer and then turns into a string when clicking on "first", but the behaviour still seems a bit buggy, since it starts to work as expected after a couple of clicks. Setting `value=0` instead of `value="0"` doesn't work either.

It's not neccessarily a bug in the validator though, it could also be that an integer is not a valid value for a radio button.

**Comment by kazupon** [comment]
@swift1
Thank you for always your reporting !! :smile_cat: 

This strange behavior caused by v-model.

Currently, `input[type='radio']` specified by `v-model` do return string value.

I think that `v-model` should support numeric value at  `input[type='radio']` too.
- Casting Value as Number
  http://vuejs.org/guide/forms.html#Casting_Value_as_Number

@yyx990803 
How about you ?
If you think you have a good about this idea, I think that will try to add `number` option on `v-model`. :)

**Comment by swift1** [comment]
@kazupon Thanks for your reply. :smile_cat:
I've tried to cast the value as a number, but it's the same bug: https://jsfiddle.net/q7xcbuxd/38/

**Comment by kazupon** [comment]
@yyx990803 

> If you think you have a good about this idea, I think that will try to add number option on v-model.

sorry my mention ... orz :bow:
In v0.12.10, This was supported.

@swift1 
Did you check to using v0.12.10 ?

**Comment by swift1** [comment]
@kazupon I just tested it with v0.12.10 now and it still doesn't work. And if I add `number` at the end (with v0.12.10), the data will always be dirty. :bow: 

https://jsfiddle.net/q7xcbuxd/40/

**Comment by kazupon** [comment]
@swift1 
I checked this issue.
I will try to fix. :smiley_cat:

**Comment by swift1** [comment]
Thanks! :smile: :smile_cat:

**Comment by kazupon** [comment]
I fixed and release v1.4.2.
Please try it. :smiley:

**Comment by swift1** [comment]
It works now: https://jsfiddle.net/q7xcbuxd/41/

Thanks man, I appreciate your work! :smile_cat: :+1:
