### ISSUE TITLE
Bug with parent elements not being set to dirty

### ISSUE THREAD

**Issue by swift1** [kazupon/vue-validator#44]
Hi! Please have a look at the following example:
https://jsfiddle.net/q7xcbuxd/39/

The parent element ("sublevel"), which also has a dirty property, never gets set to dirty, even though one of it's children become dirty.

**Comment by kazupon** [comment]
This is specification.

Currently, vue-validator don't have `dirty` property for each object hierarchy, because can not consider use-case.

**Comment by kazupon** [comment]
I published 2.0.0-alpha.1
