### ISSUE TITLE
Improvement to the resetDirtyFlags function

### ISSUE THREAD

**Issue by swift1** [kazupon/vue-validator#45]
Sup guys!

As I've mentioned earlier, I've made a custom resetDirtyFlags function so that the dirty flags can be reset during the application lifespan, for example after fetching new async data from the server. However, the previous function only worked for properties one level deep. I've now extended it to go two levels deep (ideally I'd make it recursive, but two levels will do for now).

So for example, given the following code:

```
data: {
   text: "abc",
   sub: {
       text: "abc"
   }
}
```

the improved function will now reset the dirty flags on both `text`and `sub.text`.
So in case anyone's interested, here's the code:

```
resetDirtyFlags: function(comp){
    for (var property in comp.validation) {
        //goes two levels deep
        for (var subProperty in comp.validation[property]) {
            if (comp.validation[property][subProperty].hasOwnProperty("valid")){
                //console.log(property + " " + subProperty + " " + comp.validation[property][subProperty]);
                comp.$validator._setInitialValue(property+"."+subProperty, comp.$data[property][subProperty]);
                comp.$validator._updateDirtyProperty(property+"."+subProperty, comp.$validator[property][subProperty]);
            }                   
        }
        //console.log(property);
        //goes one level deep:
        comp.$validator._setInitialValue(property, comp.$data[property]);
        comp.$validator._updateDirtyProperty(property, comp.$validator[property]);
    }
}
```

:smile_cat:

**Comment by kazupon** [comment]
I published 2.0.0-alpha.1
