### ISSUE TITLE
Bug with validator when using with component and filter

### ISSUE THREAD

**Issue by silasrm** [kazupon/vue-validator#52]
Hi,

See this link https://jsfiddle.net/silasrm/8L61dt58/4/ with developer tools/firebug open.

Explain:
My app have a list with component working with v-repeat:

<div v-repeat="itens" v-component="item-data-component">
</div>

This is ok. But I need to add a search field to searching in list item:

<input type="text" v-model="search" placeholder="Search in name..." />
And change de v-repeat to:
v-repeat="itens | filterBy search"

When I add letter, this filtering list, but when I remove letter to clear search term, occurs this error: 
Uncaught TypeError: Cannot read property 'push' of undefined

Thank's.

**Comment by kazupon** [comment]
Thank you for your reporting !!

Sorry, this is bug.
I'll try to fix.

**Comment by silasrm** [comment]
@kazupon thank you to for your lib, this is awesome.

**Comment by kazupon** [comment]
Fixed 2.0.0-alpha.1

**Comment by silasrm** [comment]
@kazupon Thank's!
