### ISSUE TITLE
Custom validators in v-repeat

### ISSUE THREAD

**Issue by gfellerph** [kazupon/vue-validator#55]
Hey, I stumbled upon this and thought it would be best to report this issue, even though I think it is being adressed in v2.0. 

I created a pen to demonstrate the behaviour (vue 0.12.13, vue-validator 1.4.3): http://codepen.io/tuelsch/pen/ojjoMR?editors=101

If the `custom` validator is used inside the `v-repeat`, a warning shows up in the console: `[vue-validator] specified invalid v-validate directive !! please check v-validator directive !!`. The built-in validator `required` works as expected (switch the attribute on the input field).

Is there a way to fix this by defining the custom validator differently or is this a bug?

Thanks for the very handy library and your effort!

**Comment by kazupon** [comment]
Hi @tuelsch !!
Thank you for your reporting !!
I checked your demonstrate code.

I think it's issue of Vue.

@yyx990803 
Does `v-repeat` pass the `vm.$options` to child vm instance ?
https://github.com/vuejs/vue-validator/blob/master/index.js#L48

**Comment by shiyala** [comment]
Hi,

@kazupon I just stumbled upon this issue. Help much appreciated.

**Comment by kazupon** [comment]
I'm implementing from scrach for v2.0 now.

I'll plan to implement the validator asset system.
https://github.com/vuejs/vue-validator/issues/41

I realized that this issue can solve with validator asset feature.
Maybe I adopt validator asset feature of v2.0 to latest of v1 (VueValidator.assets)

**Comment by kazupon** [comment]
I fixed this issue, and readied for the release of v1 latest version.

You can check behavior in the following jsfiddle.
http://jsfiddle.net/kazupon/xzhkd75c/6/

In the above jsfiddle code, I changed your [demonstrate code](http://codepen.io/tuelsch/pen/ojjoMR?editors=101), because it does not work at the `v-repeat`.
(see the https://github.com/vuejs/vue-validator/issues/31)

In order to release, we need to wait release of vue.js 0.12 latest version.
Please wait. :)

**Comment by shiyala** [comment]
Thanks much!!!!

**Comment by kazupon** [comment]
I published vue-validator latest version.
Please check it! :smiley:

**Comment by zbartl** [comment]
@kazupon This may be a 2.0 fix, but I noticed with the fiddle you posted above that, although the validation rules are applied correctly to the v-ifs, when checking {{ valid }} for any kind of submission purposes, it ignores the child rules in the components:

http://jsfiddle.net/mgnp93k0/
