### ISSUE TITLE
The child component cannot inherit validators defined in its parent.

### ISSUE THREAD

**Issue by Haixing-Hu** [kazupon/vue-validator#57]
Suppose we have a base Vue like the following

```
var base = new Vue({
  el: "#app",
  ...
  validator: {
    validates: {
      "username": require("./validator/username.js")
    }
  }
 components: {
   "my-component":  require("./my-component.vue")
 } 
});
```

and the child component is defined as follows:

```
<template>
  <input name="username" class="form-control" v-model="username"
             v-validate="required, username">
</template>
<script>
module.exports = {
  replace: true,
  inherit: true,
  data: function() {
    return  { username: "" };
  }
};
</script>
```

It seems that the child component cannot inherit validators defined in its parent.

**Comment by kazupon** [comment]
this issue is related with https://github.com/vuejs/vue-validator/issues/55

**Comment by kazupon** [comment]
I fixed this issue, and readied for the release of v1 latest version.

You can check behavior in  the following jsfiddle.
https://jsfiddle.net/kazupon/kdye3gv5/3/

In order to release, we need to wait release of vue.js 0.12 latest version.
Please wait. :)

**Comment by kazupon** [comment]
I published vue-validator latest version.
Please check it! :smiley:
