### ISSUE TITLE
Asynchronous validator should perform validation after user has finished the input

### ISSUE THREAD

**Issue by Haixing-Hu** [kazupon/vue-validator#58]
I have a form for registering new users. The form has a username field, and I use a asynchronous  validator to validate whether the username exists (as described by the example in the `README.md`).  

The problem is, the validator will try to validate as soon as the user enter a single letter. This will cause the server receives too many requests. 

Is there any way to make the asynchronous validator perform the validation after the user has finished the input? That is, the validation should be performed after the input focus leaving the username field.

Thanks in advance.

**Comment by kazupon** [comment]
Sorry for late reply.

One solution, You can achieve your asynchronous validator by using `debounce` param.
http://vuejs.org/guide/forms.html#Input_Debounce

The following example:
http://jsfiddle.net/kazupon/cm6uzjbb/2/

However, this solution is based with user input event, this solution may not be what you want.
I think that consider this issue as the development candidate of V2.
