### ISSUE TITLE
1.x branch

### ISSUE THREAD

**Issue by JoshZA** [kazupon/vue-validator#65]
Is validator going to support vue 1.x?

**Comment by kazupon** [comment]
Yes.
But current implementation of `vue-validator` does not work.

I'm developing from full-scratch as v2.0 for vue 1.x
Maybe, I think that `vue-validator` v2.0 can not publish until vue 1.0 release.

**Comment by JoshZA** [comment]
Oh that's great, looking forward to a release :smile:
