### ISSUE TITLE
Using required inside v-repeat with outside required fields breaks validation

### ISSUE THREAD

**Issue by zbartl** [kazupon/vue-validator#68]
If you use v-validate='required' within a v-repeat and no other required fields exist outside of the v-repeat, validation works as expected.

However, if you include any fields outside the v-repeat, the validation inside the v-repeat stops working: http://jsfiddle.net/kyeqemzf/

**Comment by kazupon** [comment]
Sorry for the late reply.

I checked your jsfiddle code.
In current vue-validation version for Vue 1.x, it does not work.

I'm developing vue-validator 2.0 now, however it's late because I translate vuejs.org website for japanese users.
Please wait :bow:

**Comment by kazupon** [comment]
Fixed in 2.0.0-alpha.1
