### ISSUE TITLE
Server-side validation

### ISSUE THREAD

**Issue by buzdyk** [kazupon/vue-validator#70]
Hi.

After client-side validation is ok the form data is being validated by the server side. The errors are returned in the following json format, e.g.:

```
{
    field1: errorString,
    field2: errorString,
    ...
}
```

Is there any way to tell vue-validator that these fields are invalid?

**Comment by kazupon** [comment]
Sorry for the late reply.

There is not way to tell the server-side validation errors in vue-validator.
I'll try to consider this feature in v2. :smiley_cat:

**Comment by diskman** [comment]
Is there any workaround to repopulate errors in validator on 400 response when I am getting form server http status with well described validation errors? Can I somehow access field and manualy add validation errrors for field?

`{"confirmPassword":[{"memberNames":["ConfirmPassword"],"errorMessage":"Field 'Confirm Password' can't be empty."}],"acceptTerms":[{"memberNames":["AcceptTerms"],"errorMessage":"Must be checked 'Accept Terms'."}]}`
