### ISSUE TITLE
Error : Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by intositeme** [kazupon/vue-validator#74]
I get the error immediately when i add v-validate="required" to my input tag

```
<input type="text" class="form-control" id="" placeholder="Color Fullname" v-model="formData.name" v-on:focus="onFormFocus()" v-validate="required">
```

**Comment by kazupon** [comment]
That error is occurred in Vue.js 1.0 ?

**Comment by intositeme** [comment]
Yes v1.0. Is it not supported?

**Comment by kazupon** [comment]
Sorry, it is not support yet.
I'm developing v2.0 now.
Please wait a little more. :smile_cat:

**Comment by intositeme** [comment]
oh awesome! thanks. No worries, just that i didn't find documentation stating it does not work it v1.0, so i thought i was doing something wrong. Looking forward to v2.0. 

Maybe you could update the documentation to state that it does not work with 1.0.

**Comment by kazupon** [comment]
Okay, I update README.md
https://github.com/vuejs/vue-validator#requirements
