### ISSUE TITLE
Please publish 2.0.0-alpha

### ISSUE THREAD

**Issue by CatTail** [kazupon/vue-validator#81]
I am using  Vue.js ^1.0 and vue-validator can't work as expected

**Comment by calebporzio** [comment]
+1

**Comment by blueshed** [comment]
+1

**Comment by voxtobox** [comment]
Have you tried [Vue migration](https://github.com/vuejs/vue/releases/tag/1.0.0-migration)? I'm using it with Vue-strap until new version release. There are many warnings but it works.

**Comment by kazupon** [comment]
sorry... everyone.

I'm busy with the work.
I'm developing the v2.0 in incremental steps though. (Please see  https://github.com/vuejs/vue-validator/commits/dev/latest)

When I finished basic validation feature implemetation, I'll publish as 2.0-alpha.1

Please wait.
