### ISSUE TITLE
Keep getting Failed to resolve directive: validate

### ISSUE THREAD

**Issue by FWSimon** [kazupon/vue-validator#93]
Hey,

I have installed Vue-validator `1.4.4` and set it all up but i keep getting `Failed to resolve directive: validate` i just used the example

```
<validator name="validation1">
  <form novalidate>
    <input type="text" v-validate:username.required>
    <input type="text" v-validate:comment.maxlength="256">
    <div>
      <span v-show="$validation1.username.required">Rquired your name.</span>
      <span v-show="$validation1.comment.maxlength">Your comment is too long.</span>
    </div>
    <input type="submit" value="send" v-if="$validation1.valid">
  </form>
</validator>
```

What can i have done wrong?

**Comment by kazupon** [comment]
Hi :smile_cat: 

The above codes doesn't work `1.4.4`.
You can upgrade to 2.0.0-alpha latest version.

Please try it :smile_cat:

**Comment by abbymrs** [comment]
Hi,
i have the same issue with vue@2.1.1, vue-validator@3.0.0-alpha.2
