### ISSUE TITLE
Validation not revalidated when model updated programmatically.

### ISSUE THREAD

**Issue by nigelmst** [kazupon/vue-validator#94]
See [jsfiddle](http://jsfiddle.net/aggota9j/1/)

`description` is set after 2 seconds and `valid` remains `false`. Is there  a way to force revalidation?

**Comment by kazupon** [comment]
sorry, `v-model` can not support yet.
I'll try to implement.

**Comment by nigelmst** [comment]
Thanks @kazupon 

That will be really useful as I am populating the form by doing an AJAX call to fetch data, but the validations are out of sync with the data.

**Comment by ferry77** [comment]
+1 :)

**Comment by 0xara** [comment]
+1
