### ISSUE TITLE
can i use `v-validate` directive on a component( not form inputs )?

### ISSUE THREAD

**Issue by ccqgithub** [kazupon/vue-validator#96]
can i use `v-validate` directive on a component( e.g. a custom style checkbox )?

however, i can use a hidden input to bind `v-validate`, but if i do this, the `touched` propertie can be right ?

**Comment by kazupon** [comment]
sorry, currently, vue-validator cannot validate with `v-validate` for user custom input.
I want to see the example codes because I don't understand this use case.

**Comment by ccqgithub** [comment]
@kazupon e.g. I custom a select elements `my-select`, i want do like this :

```
<validator name="loginValidator">
<form>
    <my-select :options="options" :value.sync="value" v-validate:age.required></my-select>
    <div v-if="$loginValidator.age.invalid && $loginValidator.age.touched">required</div>
</form>
</validator>
```

It does not work, so I can do ti like this:

```
<validator name="loginValidator">
<form>
    <my-select :options="options" :value.sync="value"></my-select>
    <input :value="value" hidden v-validate:age.required></input>
    <div v-if="$loginValidator.age.invalid && $loginValidator.age.touched">required</div>
</form>
</validator>
```

But the input is hidden, can trigger `touched` property ?

**Comment by kazupon** [comment]
Thanks for your example code :)

> But the input is hidden, can trigger touched property ?

Unfortunately I cannot do it at current vie-validator alpha version.

I'll try to support user custom element select2-like.
https://github.com/vuejs/vue-validator/issues/50

**Comment by ccqgithub** [comment]
Glad to hear that ……

**Comment by lazabogdan** [comment]
@ccqgithub Have you found a better way by any chance? Have you sticked to the `hidden` input, or what's your current approach?

@kazupon Any news on this subject?

**Comment by ccqgithub** [comment]
@lazabogdan now, i use `v-model` with `hidden input`.

**Comment by kazupon** [comment]
Close (exist #186)
